chore(docs): improve version picker
angular/angular.js pull request #15385
Opened 2016-11-10 21:58 UTC by petebacondarwin

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

chore

**What is the current behavior? (You can also link to an open issue here)**

Versions in the version picker are hard-coded into each build
This means that newer versions are never shown in older versions of the docs

**What is the new behavior (if this is a feature change)?**

Now the version information has split into the current and the list of all versions.
In the production deployment the version list is now read from the snapshot build, so we always
get the latest list.

**Does this PR introduce a breaking change?**

No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

Replaces #15381

2016-11-10 21:59 UTC, petebacondarwin commented on docs/config/services/deployments/production.js
> +      'https://code.angularjs.org/snapshot/docs/js/versions-data.js',
note that in production we read the list from snapshot
otherwise we just use the local

2016-11-12 15:55 UTC, petebacondarwin commented on docs/config/services/deployments/production.js
> +      'https://code.angularjs.org/snapshot/docs/js/versions-data.js',
This will require some CORS setup on code.angularjs.org I think

2016-11-14 08:21 UTC, petebacondarwin commented on docs/config/services/deployments/production.js
> +      'https://code.angularjs.org/snapshot/docs/js/versions-data.js',
actually no it won't because we are loading via a script not XHR

2016-11-14 08:23 UTC, petebacondarwin commented
We could change the docs apps for most releases on code.angularjs.org to use this same code.

2016-11-14 14:25 UTC, Narretz requested changes
A few minor things that shold be clarified, otherwise I really like the solution.

2016-11-14 14:25 UTC, Narretz commented on docs/config/processors/versions-data.js
> +      var blacklist = this.blacklist;
What's the meaning of the blacklist? Can you please add a comment?

2016-11-14 20:52 UTC, petebacondarwin commented on Gruntfile.js
> +  grunt.registerTask('package', ['bower', 'validate-angular-files', 'clean', 'buildall', 'minall', 'collect-errors', 'write', 'docs', 'copy', 'compress']);
This is because the version.json file is generated by the `write` grunt task. So we need it to run before the `docs` task, which now relies upon it.

2016-11-14 20:53 UTC, petebacondarwin commented on docs/config/processors/versions-data.js
> +      var blacklist = this.blacklist;
OK. The main reason was that we appear to have npm published a random rogue release, 1.3.4-build.3588, which does not have an associated folder on code.angularjs.org

2016-11-14 23:09 UTC, gkalpak requested changes

2016-11-14 23:09 UTC, gkalpak commented on docs/config/processors/versions-data.js
> +          .filter(function(version) {
AFAICT, filtering after having populated `latestMap`, will allow `0.x` versions to appear in the "Latest" group of the dropdown. The filtering should be done before populating ``latestMap`.

2016-11-15 08:38 UTC, gkalpak commented
Not directly related to this PR, but close enough:
I miss showing the build number in the version picker for snapshot releases.

2016-11-15 08:53 UTC, Narretz commented on docs/config/processors/versions-data.js
> +          .filter(function(version) {
I can't reproduce this locally. It also looks like we don't include any 0.x versions at all.

2016-11-15 08:55 UTC, Narretz commented
The build number is shown on the api docs home page. Why do you want to have it in the picker?

2016-11-15 09:47 UTC, gkalpak commented
Convenience :) It makes it easy to see when refreshing the page gets you a newer build.
It's probably only useful to me, not to our users :)

2016-11-15 09:48 UTC, gkalpak commented on docs/config/processors/versions-data.js
> +          .filter(function(version) {
I didn't try it locally, but from looking at the code I assumed that 0.x versions would be shown in the "Latest" group. Are you sure they are not there (only in the "Latest" group though).

2016-11-15 09:51 UTC, petebacondarwin commented
I think we should display the build number of the docs somewhere on the page. Perhaps near the bottom?

2016-11-15 10:42 UTC, Narretz commented
The build number is displayed in the footer. :D

2016-11-15 11:02 UTC, gkalpak commented
Right. But you have to scroll all the way down to see the footer :smiley:
Anyway, it is probably not worth making it more convenient for me/us, if it is something that most users don't care about. The info is there if someone needs it (even if they have to scroll :smiley:).

2016-11-15 11:17 UTC, gkalpak approved these changes

2016-11-15 11:18 UTC, gkalpak commented
LGTM as long as Travis is happy.

2016-11-15 11:56 UTC, petebacondarwin commented
Travis is not happy but it is an east fix

2016-11-15 12:11 UTC, petebacondarwin commented
Travis is now happy - after a copied the all-versions.js file onto the snapshot :-)

2016-11-15 12:13 UTC, merged

2016-11-28 10:32 UTC, petebacondarwin commented
See https://github.com/angular/angular.js/commit/48362788303a70d9e4ab36e672ec68a4ce5645c3