docs($compile): add double compilation known issue
angular/angular.js pull request #15392
Opened 2016-11-15 09:03 UTC by Narretz

2016-11-15 10:58 UTC, gkalpak requested changes
We could also put that in the compiler guide (with a short note here in the API docs that double-compilation is not supported).

2016-11-15 10:58 UTC, gkalpak commented on src/ng/compile.js
> + * attached again to the ngModelController. It can also degrade performance, as
>  `ngModel` $formatters and $parsers will be attached again to the ngModelController

Why? `ngModel` seems to only be compiled once.

2016-11-15 10:58 UTC, gkalpak commented on src/ng/compile.js
> + * Double compilation should therefore avoided. In the above example, the better way is to only
_avoided_ --> _be avoided_

2016-11-15 10:58 UTC, gkalpak commented on src/ng/compile.js
> + * Double compilation should therefore avoided. In the above example, the better way is to only
_the better way_ --> _a better way_ (?)

2016-11-15 10:58 UTC, gkalpak commented on src/ng/compile.js
> +        element.append(newEl);
I think usually it is preferrable to first append the element and then compile it, in order to have proper context (e.g. requiring parent directive controllers).

2016-11-15 10:58 UTC, gkalpak commented on src/ng/compile.js
> +        attrs.$set('addInput', null) // To stop infinite compile loop
_addInput_ --> _addOptions_

2016-11-15 10:58 UTC, gkalpak commented on src/ng/compile.js
> + * 1. give your directive the `terminal` property and a higher priority than directives
Capitalize these sentences.

2016-11-15 10:58 UTC, gkalpak commented on src/ng/compile.js
> + * and add any other directive attributes. Removing the attribute is necessary, because otherwise the
You don't need to remove the attribute, since you pass the priority to `$compile`.

2016-11-15 17:05 UTC, Narretz commented on src/ng/compile.js
> + * attached again to the ngModelController. It can also degrade performance, as
True, I was actually thinking of an issue with replace. I will change the example.

2016-11-15 17:36 UTC, Narretz commented
I've updated the example and moved it to the compiler guide, and added a short paragraph with a link to the compile api docs

2016-11-15 18:02 UTC, gkalpak requested changes

2016-11-15 18:02 UTC, gkalpak commented on docs/content/guide/compiler.ngdoc
> +      element.on('mouseenter mouseout', function() {
The opposite of `mouseenter` is `mouseout` :grin:

2016-11-15 18:02 UTC, gkalpak commented on docs/content/guide/compiler.ngdoc
> +angular.module('app').directive('addMouseover', function($compile) {
We should have a big, fat comment or a danger alert that this is what you should NOT do. People tend to get confused when the docs show bad examples to be avoided.

2016-11-15 18:02 UTC, gkalpak commented on docs/content/guide/compiler.ngdoc
> +      attrs.$set('addMouseover', null);
No need to remove this any more.

2016-11-15 18:02 UTC, gkalpak commented on docs/content/guide/compiler.ngdoc
> +compile again.
Again, lets make it clear this is a BAD thing.

2016-11-15 18:02 UTC, gkalpak commented on docs/content/guide/compiler.ngdoc
> +  compilation would result in an infinite loop.
You don't need to remove the attribute, since you pass the priority to $compile.

2016-11-15 18:02 UTC, gkalpak commented on docs/content/guide/compiler.ngdoc
> +    template: '<input ng-model="$ctrl.value">',
You don't want to have a template.

2016-11-17 18:18 UTC, Narretz commented on docs/content/guide/compiler.ngdoc
> +      element.on('mouseenter mouseout', function() {
Sorry, I don't understand. Do you mean it should be `mouseleave`?

2016-11-17 18:18 UTC, Narretz commented on docs/content/guide/compiler.ngdoc
> +angular.module('app').directive('addMouseover', function($compile) {
I agree, but we should have a general solution to this.

2016-11-17 19:11 UTC, Narretz commented on docs/content/guide/compiler.ngdoc
> +angular.module('app').directive('addMouseover', function($compile) {
I tried putting a div around it, but then the code blocks aren't rendered correctly. Seems to be an issue with the marked library: https://github.com/chjj/marked/issues/596

2016-11-22 21:10 UTC, Narretz commented
I've updated the PR @gkalpak PTAL

2016-11-22 21:41 UTC, gkalpak approved these changes
A couple of typos.
LGTM otherwise 👍

2016-11-22 21:41 UTC, gkalpak commented on docs/content/guide/compiler.ngdoc
> +      element.on('mouseenter mouseout', function() {
This is still `mouseout` 😞

2016-11-22 21:41 UTC, gkalpak commented on docs/content/guide/compiler.ngdoc
> +  4. In the link function, link the compiled element with the element's scope
Missing period at the end.

2016-11-22 21:41 UTC, gkalpak commented on docs/content/guide/compiler.ngdoc
> +```
Should this be ```` ```js ```` (here and below) or does marked autodetect JS?

2016-11-22 21:41 UTC, gkalpak commented on docs/content/guide/compiler.ngdoc
> +angular.module('app').directive('addMouseover', function($compile) {
I would still prefer a comment above this line; something like:

```js
// BAD - Don't do this
```

And an equivalent comment in the recommended alternatives; e.g.:

```js
// OK - You can do this
```

But I can leave without if you think it's too much. Up to you.

2016-11-22 22:19 UTC, Narretz commented on docs/content/guide/compiler.ngdoc
> +```
I always thought it auto-detects

2016-11-22 22:22 UTC, Narretz commented
I think the part about `mouseout/leave` is broken on Github's UI. You can see that it's mouseleave in the file at the latest fixup commit. It just shows wrongly in the "Files Changed" view. I can also not comment on it from the comment view.

2016-11-22 22:26 UTC, Narretz commented on docs/content/guide/compiler.ngdoc
> +angular.module('app').directive('addMouseover', function($compile) {
I'll leave it as is, and we'll see how soon someone stumbles over this

2016-11-23 07:50 UTC, gkalpak commented
There were two occurrences of `mouseout`. Yo have replaced the second one with `mouseleave`, but there is still one more (on line 397).

2016-11-23 12:05 UTC, Narretz commented
Omg ...

2016-11-23 12:13 UTC, gkalpak approved these changes
LGTM (as soon as travis is happy)

2016-11-23 12:52 UTC, merged