fix(ngResource): do not eat exceptions in success callback
angular/angular.js pull request #15628
Opened 2017-01-19 20:19 UTC by kylewuolle

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix

**What is the current behavior? (You can also link to an open issue here)**
Addresses bug identified in `https://github.com/angular/angular.js/issues/15624`

**No error message is output in the console:**
```
var User = $resource('users/:id', {id: '@id'});
var user User.get({id: 123}, function (res) {
    y  = x + z; // this line not log any exception on the console
}, function () {
    console.log(arguments);
});
```
**Error message is output in the console:**

```
var User = $resource('users/:id', {id: '@id'});
var user User.get({id: 123}, function (res) {
    y  = x + z; // and this log the exception in the console
});
```

**What is the new behavior (if this is a feature change)?**
Now any exceptions thrown in the success callback will be thrown and not eaten.

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [X ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-01-26 21:29 UTC, gkalpak requested changes
The implementation looks good. I've left a comment regarding the tests.

2017-01-26 21:29 UTC, gkalpak commented on test/ngResource/resourceSpec.js
> +  describe('exception handling in callbacks', function() {
These tests should be incorporated into the [errors block][1]. Also, can you add tests for all 4 combinations (no errorCallback/no responseErrorInterceptor, no errorCallback/yes responseErrorInterceptor, yes errorCallback/no responseErrorInterceptor, yes errorCallback/yes responseErrorInterceptor).

[1]: https://github.com/kylewuolle/angular.js/blob/982a063507f649bde84b727dcc2cefcf3e0bbcd3/test/ngResource/resourceSpec.js#L1618

2017-02-03 17:22 UTC, kylewuolle commented on test/ngResource/resourceSpec.js
> +  describe('exception handling in callbacks', function() {
thanks I made the changes requested!

2017-02-03 18:24 UTC, kylewuolle commented
Thanks I made the changes

2017-02-04 09:52 UTC, gkalpak requested changes

2017-02-04 09:52 UTC, gkalpak commented on test/ngResource/resourceSpec.js
> +    var CreditCard = $resource('/CreditCard/:id:verb', { id: '@id.key' });
Remove the unnecessary bits (here and below). E.g.:

```js
$httpBackend.expect('GET', '/CreditCard/123').respond(null);
var CreditCard = $resource('/CreditCard/:id');
```

2017-02-04 09:52 UTC, gkalpak commented on test/ngResource/resourceSpec.js
> +  it('should throw exception in success callback when error callback provided and no responseErrorInterceptor', function() {
Change the tests descriptions to something like:

> should not swallow exception in success callback...

2017-02-04 09:52 UTC, gkalpak commented on test/ngResource/resourceSpec.js
> +          interceptor: { responseError: function() { return $q.reject({}); } }
Make this a non-rejecting interceptor.

2017-02-04 09:52 UTC, gkalpak commented on test/ngResource/resourceSpec.js
> +          interceptor: { responseError: function() { return $q.reject({}); } }
Make this a non-rejecting interceptor.

2017-02-04 17:27 UTC, kylewuolle commented
Thanks I fixed up the tests etc

2017-02-04 18:41 UTC, gkalpak approved these changes

2017-02-04 18:42 UTC, gkalpak commented
LGTM 👍
<sub>I'll clean up the tests a bit more (e.g. remove unused default params (`{ id: '@id.key' }`)) and merge.</sub>

2017-02-04 19:01 UTC, closed without merging