docs(*): ensure naming is correct for Angular(JS) versions
angular/angular.js pull request #15638
Opened 2017-01-24 15:16 UTC by petebacondarwin

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-01-24 16:52 UTC, gkalpak requested changes
Only a couple of blocking comments (and a couple more non-blocking).

When I first saw the changes in the SVG images for the tutorial, I thought: "Yay! SVG ftw!"
Then I remembered we use PNGs (derived from the SVGs) in the tutorial. So, we need to update those too at some point (not necessarily as part of this PR) 😞

2017-01-24 16:52 UTC, gkalpak commented on docs/content/error/$injector/modulerr.ngdoc
> +### Monkey-patching AngularJS's `ng` module
Should there be an `s` after `'` (since `AngularJS` ends in `S`)?

2017-01-24 16:52 UTC, gkalpak commented on docs/content/guide/component-router.ngdoc
> +We are investigating backporting the Angular Router to AngularJS, but alternatively, use the {@link ngRoute} module or community developed projects (e.g. [ui-router](https://github.com/angular-ui/ui-
I feel this is a little confusing (Angular and AngularJS on the same sentence). What is the guideline for places were Angular and AngularJS are used side-by-side? I think a clarification (e.g. at the top of the page) would be nice.

2017-01-24 16:52 UTC, gkalpak commented on docs/content/error/$injector/modulerr.ngdoc
> +### Monkey-patching AngularJS's `ng` module
Hm...according to [this][1] it's fine.

[1]: http://data.grammarbook.com/blog/apostrophes/apostrophes-with-words-ending-in-s/

2017-01-24 16:52 UTC, gkalpak commented on docs/content/guide/production.ngdoc
> +In order to perform this task, the AngularJS compiler must look for directives by:
💯

2017-01-24 16:52 UTC, gkalpak commented on docs/content/tutorial/step_09.ngdoc
> +    "angular-route": "1.6.x",
I don't think these changes (here and elsewhere) are correct. The tutorial still uses 1.5.x iirc.

2017-01-24 16:52 UTC, gkalpak commented on src/ng/compile.js
> + * Angular also uses life-cycle hooks for its components. While the AngularJS life-cycle hooks are similar there are
Again, I feel this is a little confusing.

2017-01-24 16:52 UTC, gkalpak commented on test/e2e/tests/ng-route-promise.spec.js
> +      expect(error.message).toContain('Timed out waiting for asynchronous AngularJS tasks to finish');
This will fail, because the error message is generated by Protractor (not us).

2017-01-24 16:52 UTC, gkalpak commented on test/e2e/tests/angular-already-loaded.spec.js
> +describe('App where angAngularJSular is loaded more than once', function() {
Typo.

2017-01-24 16:52 UTC, gkalpak commented on src/ngComponentRouter/Router.js
> + * In an effort to keep synchronized with router changes in Angular, this implementation of the
Here too: A little confusing.

2017-01-24 16:53 UTC, gkalpak commented
I only consider [this][1] and [that][2] blocking.

[1]: https://github.com/angular/angular.js/pull/15638#discussion_r97590224
[2]: https://github.com/angular/angular.js/pull/15638#discussion_r97593070

2017-01-24 17:12 UTC, petebacondarwin commented on docs/content/tutorial/step_09.ngdoc
> +    "angular-route": "1.6.x",
Yeah I was going to follow it up with changes to phonecat but I guess this should be done in a different PR

2017-01-24 17:12 UTC, petebacondarwin commented on test/e2e/tests/ng-route-promise.spec.js
> +      expect(error.message).toContain('Timed out waiting for asynchronous AngularJS tasks to finish');
Gadzooks!

2017-01-24 17:13 UTC, petebacondarwin commented on test/e2e/tests/angular-already-loaded.spec.js
> +describe('App where angAngularJSular is loaded more than once', function() {
oops

2017-01-24 17:13 UTC, petebacondarwin commented on docs/content/error/$injector/modulerr.ngdoc
> +### Monkey-patching AngularJS's `ng` module
Yeah it can go either way

2017-01-24 17:16 UTC, petebacondarwin commented on docs/content/guide/component-router.ngdoc
> +We are investigating backporting the Angular Router to AngularJS, but alternatively, use the {@link ngRoute} module or community developed projects (e.g. [ui-router](https://github.com/angular-ui/ui-
I felt that having them so close would be enough (along with our other communications about this that will happen). But I can add the word "new" in front of Angular to make it a bit clearer.

2017-01-24 17:28 UTC, gkalpak approved these changes
LGTM (with one optional comment :smiley:)

2017-01-24 17:28 UTC, gkalpak commented on test/e2e/tests/angular-already-loaded.spec.js
>  'use strict';
Why not change the name of this file as well?

2017-01-24 21:26 UTC, IgorMinar commented
LGTM! Thanks for getting this out so quickly

2017-01-25 09:23 UTC, petebacondarwin commented
Landed as 03043839d5a540b02208001fe12e812dfde00a8e

2017-01-25 09:23 UTC, closed without merging