filter(filter): Don't throw `key.charAt is not a function` when object's keys are not of type `string`.
angular/angular.js pull request #15660
Opened 2017-02-01 07:22 UTC by frederikprijck

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix

**What is the current behavior? (You can also link to an open issue here)**
When an object has keys which are not of type string, the `filter` would throw an exception for trying to call `charAt`, which is not defined on a none-string type.

#15644

**What is the new behavior (if this is a feature change)?**
This commit checks whether `charAt` is defined before calling it.

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-02-01 12:18 UTC, Narretz commented
Can you please add a test for this?

2017-02-01 14:58 UTC, gkalpak commented
I am afraid it is not possible (as discussed in #15644) :grin:

2017-02-01 15:02 UTC, gkalpak requested changes

2017-02-01 15:02 UTC, gkalpak commented on src/ng/filter/filter.js
> +          if (key.charAt && (key.charAt(0) !== '$') && deepCompare(actual[key], expected, comparator, anyPropertyKey, true)) {
Add a comment (and maybe a link to the issue) for context. Something like:

> Under certain, extreme circumstances, `key` may not be a string. See ...`

2017-02-01 18:58 UTC, frederikprijck commented on src/ng/filter/filter.js
> +          if (key.charAt && (key.charAt(0) !== '$') && deepCompare(actual[key], expected, comparator, anyPropertyKey, true)) {
I've added some comment.

2017-02-01 18:59 UTC, gkalpak approved these changes

2017-02-01 19:00 UTC, gkalpak commented
LGTM if it LGT @Narretz :smiley:

2017-02-08 18:41 UTC, Narretz commented
LGTM

2017-02-08 21:18 UTC, closed without merging