fix($window): allow $window to be mocked in unit tests
angular/angular.js pull request #15686
Opened 2017-02-07 17:51 UTC by mattlewis92

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix

**What is the current behavior? (You can also link to an open issue here)**
https://github.com/angular/angular.js/issues/15685

**What is the new behavior (if this is a feature change)?**
N/A

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] <s>Docs have been added / updated (for bug fixes / features)</s>

**Other information**:

2017-02-07 19:45 UTC, gkalpak requested changes
Can you also change the commit message to `fix($jsonpCallbacks): ...`?

2017-02-07 19:45 UTC, gkalpak commented on src/ng/jsonpCallbacks.js
> +    var callbacks = $window.angular ? $window.angular.callbacks : {};
Actually, I think it makes more sense to just use `angular` directly:

```diff
-     var callbacks = $window.angular.callbacks;
+     var callbacks = angular.callbacks;
```

2017-02-07 19:56 UTC, mattlewis92 commented
@gkalpak done 😄

2017-02-07 20:16 UTC, gkalpak commented on src/ng/jsonpCallbacks.js
> +  this.$get = [function() {
We don't need the `[...]` now. It can be just `this.$get = function() {...`

2017-02-07 20:30 UTC, mattlewis92 commented on src/ng/jsonpCallbacks.js
> +  this.$get = [function() {
Done

2017-02-07 23:39 UTC, mattlewis92 commented
CI failure is a flake - the API limit on saucelabs has been hit

2017-02-08 13:34 UTC, gkalpak approved these changes

2017-02-08 16:10 UTC, closed without merging