fix(angular.copy) support for Map and Set
angular/angular.js pull request #15697
Opened 2017-02-09 18:27 UTC by mrohr

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
bug fix

**What is the current behavior? (You can also link to an open issue here)**
the copied Map or Set will fail to call functions with an error such as:
TypeError: Method Map.prototype.size called on incompatible receiver #<Map>

**What is the new behavior (if this is a feature change)?**
angular.copy will now property create new Map or Set objects with the same values as the source.

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-02-09 18:29 UTC, mrohr commented
signed!

2017-02-09 18:34 UTC, mrohr commented
updated email for CLA

2017-02-10 22:39 UTC, frederikprijck commented
@mrohr I did some digging in the reason why the tests was failing IE11, it looks like `Object.prototype.toString.call(source)` (https://github.com/mrohr/angular.js/blob/d5dbb5973b4588e75afee9d81a0f008f69dc033d/src/Angular.js#L997) evaluate to `[object Object]` in IE11, resulting in the usage of `Object.create(Object.getPrototypeOf(source)` to copy instead of your code. 
This throws the exception you're getting when accessing `size` on the destination object: `Map.prototype.size: 'this' is not a Map object`.

I created a fiddle to demonstrate the issue outside angularjs: https://jsfiddle.net/0mstLj6q/7/

Opening this plunkr in IE11 (Windows 10) shows:

![image](https://cloud.githubusercontent.com/assets/2146903/22846840/f4b6c05e-efe9-11e6-9f73-5f8ac6d32650.png)

2017-02-20 08:24 UTC, gkalpak requested changes

2017-02-20 08:24 UTC, gkalpak commented on src/Angular.js
> +        var copiedMap = new Map();
We access globals through the `window` in order to support non-browser environments (such as jsdom).

2017-02-20 08:24 UTC, gkalpak commented on src/Angular.js
> +        source.forEach(function(value, key) {
Wouldn't `return new Map(source)` work as well?

2017-02-20 08:50 UTC, frederikprijck commented on src/Angular.js
> +        source.forEach(function(value, key) {
If I understand this correctly, IE11 does not support Map and Set constructor with arguments ? https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Map

2017-02-20 17:13 UTC, jbedard commented on src/Angular.js
> +        source.forEach(function(value, key) {
This also needs to copy the keys/values, not just assign them, probably by invoking `copyRecurse` so we also get the `maxDepth` behavior.

2017-02-21 15:51 UTC, mrohr commented on src/Angular.js
> +        var copiedMap = new Map();
I had originally used new source.constructor() here, tried changing it to Map/Set to deal /w the IE11 issue that is failing the build.  My next update I will change it back

2017-02-21 16:00 UTC, mrohr commented
@frederikprijck Thanks for your help, I'm guessing this feature is pretty much stuck, unless we set up the tests to not run in browsers that don't print map/set objects .toString() as '[object Map]'/'[object Set]'?

2017-02-21 17:21 UTC, frederikprijck commented
Or are there alternative approaches available to detect Map and Set in IE11 (or all browsers)?

I just did some debugging and this validates to true in IE11:

````
source.constructor === Map;
Object.getPrototypeOf(source) === Map.prototype;
```
aswell as
````
source.constructor === Set;
Object.getPrototypeOf(source) === Set.prototype;
```

2017-02-28 08:32 UTC, gkalpak commented
There are a couple of problems with this feature (which are not specific to the feature itself, rather general problems with similar features):

1. In order to be able to reliably use the feature throughout AngularJS, other internal helpers need to support it too (e.g. `equals()`). Supporting a feature in `copy()` only, is useful when using `copy()` as a general helper utility, but this is not its purpose and adds extra size and maintenance overhead.

2. It is really difficult to ensure that the feature works reliably and consistently across browsers and browser versions, because it relies on JS features that are not supported by all browsers, are fairly new additions (which means browser implementations are buggy and may change frequently) and are only partially supported by some browsers (which makes it even more difficult to rely upon or polyfill).

For these reasons, I am going to put it in the Ice Box for now (but I am open to being convinced otherwise - now or in the future :smiley:).
In any case, thx for working on this @mrohr 👍

2019-01-21 14:50 UTC, closed without merging