doc($sce): Overhaul the $sce service's documentation.
angular/angular.js pull request #15735
Opened 2017-02-21 14:20 UTC by rjamet

A big docs update around the $sce: there's a lot of content in there that's often misunderstood, and some of the documentation starts to get really old too. Plus some minor falsehoods in there... Overall, this isn't a major refactoring, but there's a lot of smaller changes.

cc @mprobst for another set of eyes on the contents.

**Does this PR introduce a breaking change?**
Nope, it's a doc-only CL.

**Other information**:
- I haven't tested how the doc renders, as I couldn't find a way to do so ?

2017-02-21 16:17 UTC, mprobst commented on src/ng/sce.js
> +     *   of your `value` in URL context (currently unused.)
(currently untrusted) is a bit misleading, maybe `used as a trusted variant of your previously untrusted value`?

2017-02-22 13:03 UTC, rjamet commented on src/ng/sce.js
> +     *   for use.  e.g. url, resourceUrl, html, js and css.
Should I do that for the whole file, while I'm at it? Do you have a style guide for doc?

2017-02-22 13:06 UTC, mprobst commented on src/ng/sce.js
> +     *   for use.  e.g. url, resourceUrl, html, js and css.
Please do. I don't think we have a style guide in Angular, but +4 matches Google JS style and what you generally do in other languages.

2017-02-22 13:13 UTC, rjamet commented on src/ng/sce.js
> +     *   for use.  e.g. url, resourceUrl, html, js and css.
Ok, I'll do that. 80 or 100 cols, btw?

2017-02-22 13:49 UTC, rjamet commented on src/ng/sce.js
> +     * passed as a string will cause it to be sanitized.
Added "Note that in most cases you won't need to call trustAsHtml: if you have the sanitizer loaded, passing the value itself will render all HTML that does not pose a security risk."

2017-02-22 13:50 UTC, rjamet commented on src/ng/sce.js
> +     * used as-is, without any security check, by sinks that use this context.
I've replaced it by "used as is without any security checks by bindings or directives that require this security context."

2017-02-22 13:50 UTC, rjamet commented on src/ng/sce.js
> +     * trusted representation of it. This trusted object should later on be
Yup, done.

2017-02-22 13:50 UTC, rjamet commented on src/ng/sce.js
> +     * Marks the parameter as trusted for the specified context, and returns the
Yup, right, my formulation might imply that there's a global list of trusted stuff somewhere. Changed to "Returns a trusted representation of the parameter for the specified context. "

2017-02-22 13:51 UTC, rjamet commented on src/ng/sce.js
> +     *   of your `value` in URL context (currently unused.)
it's unused, not untrusted. Fixed by saying that

2017-02-22 13:53 UTC, rjamet commented
Some more formatting fixes after your comments:
- +4 spaces for indents
- 100 col everywhere
- s/@returns/@return/
- I uniformized context names : it's not "x for a kind of context" anymore, just "x for context", and always refer to them with the form `$sce.HTML` 
- a bunch of backticks here and there

2017-02-22 14:11 UTC, mprobst commented
LGTM.

2017-02-22 14:11 UTC, mprobst approved these changes

2017-02-28 09:24 UTC, gkalpak requested changes

2017-02-28 09:24 UTC, gkalpak commented on src/ng/sce.js
> +     * @param {*} value The value that that should be considered trusted.
_that that_ --> _that_

2017-02-28 09:24 UTC, gkalpak commented on src/ng/sce.js
> +     * In practice, there's several cases. When given a string, this run checks and sanitization to
_there's_ --> _there are_
_this run_ --> _it runs_

2017-02-28 09:24 UTC, gkalpak commented on src/ng/sce.js
> +     * ng.$sceDelegate#trustAs `$sceDelegate.trustAs`} call, this returns the originally supplied
_this_ --> _it_ (we generally try to avoid "this" as it can be confusing)

2017-02-28 09:24 UTC, gkalpak commented on src/ng/sce.js
> +     * @return {*} A version of value that's safe to use in the given context, or throws an
_of value_ --> _of the value_

2017-02-28 09:24 UTC, gkalpak commented on src/ng/sce.js
> + * before rendering if a sanitizer is available, and throw otherwise. To render the input as-is, you
To make this more obvious, I might prepend: _"To bypass sanitization and render the input as-in..."_

2017-02-28 09:24 UTC, gkalpak commented on src/ng/sce.js
> + * received from your server, sanitized by your library, etc.. You can organize your codebase to
_etc.._ --> _etc._

2017-02-28 09:24 UTC, gkalpak commented on src/ng/sce.js
> + * also use the `$sanitize` injectable if it is available when binding untrusted values to
_injectable_ --> _service_ (It would be clearer to the reader, as this is the term we use throughout the docs.)

2017-02-28 09:24 UTC, gkalpak commented on src/ng/sce.js
> +     *     of your `value` in CSS context. This context is currently unused, so there are almost no
_CSS_ --> _\`$sce.CSS\`_ (?)

2017-02-28 09:24 UTC, gkalpak commented on src/ng/sce.js
> +     * as-is. Finally, this function can also throw when there is no way to turn maybeTrusted in a
_maybeTrusted_ --> _\`maybeTrusted\`_

2017-02-28 09:24 UTC, gkalpak commented on src/ng/sce.js
> +     * @return {*} The value the was originally provided to {@link ng.$sce#trustAs `$sce.trustAs`}
_the was_ --> _that was_

2017-02-28 09:29 UTC, gkalpak commented
BTW, regarding the 4-space indentation on `@param` or `@return` descriptions: I think that is some cases (e.g. when there are bullet-points or empty lines) dgeni will recongnize this indended blocks as code blocks and wrap them in `<pre>` tags. Have you checked the rendered output?

2017-03-03 14:51 UTC, rjamet commented on src/ng/sce.js
> +     * as-is. Finally, this function can also throw when there is no way to turn maybeTrusted in a
Done

2017-03-03 14:52 UTC, rjamet commented on src/ng/sce.js
> +     * @return {*} The value the was originally provided to {@link ng.$sce#trustAs `$sce.trustAs`}
done

2017-03-03 14:52 UTC, rjamet commented on src/ng/sce.js
> +     *     of your `value` in CSS context. This context is currently unused, so there are almost no
I missed that one. Fixed.

2017-03-03 14:52 UTC, rjamet commented on src/ng/sce.js
> + * also use the `$sanitize` injectable if it is available when binding untrusted values to
Yes, right

2017-03-03 14:52 UTC, rjamet commented on src/ng/sce.js
> + * received from your server, sanitized by your library, etc.. You can organize your codebase to
done

2017-03-03 14:52 UTC, rjamet commented on src/ng/sce.js
> + * before rendering if a sanitizer is available, and throw otherwise. To render the input as-is, you
That's better, yes. fixed.

2017-03-03 14:52 UTC, rjamet commented on src/ng/sce.js
> +     * @return {*} A version of value that's safe to use in the given context, or throws an
done

2017-03-03 14:52 UTC, rjamet commented on src/ng/sce.js
> +     * ng.$sceDelegate#trustAs `$sceDelegate.trustAs`} call, this returns the originally supplied
done (plus another this above clarified in this function)

2017-03-03 14:52 UTC, rjamet commented on src/ng/sce.js
> +     * In practice, there's several cases. When given a string, this run checks and sanitization to
done

2017-03-03 14:52 UTC, rjamet commented on src/ng/sce.js
> +     * @param {*} value The value that that should be considered trusted.
done

2017-03-03 14:52 UTC, rjamet commented on src/ng/sce.js
> +   *     **Note:** the default whitelist of 'self' is not recommanded if your app shares its origin
done

2017-03-03 14:54 UTC, rjamet commented
I don't know how to render these so far, so everything is blind edits... I'll look into dgeni.

2017-03-04 22:12 UTC, gkalpak commented
My only concern is whether the 4-space indentations make some blocks incorrectly rendered as code blocks. Other than that it LGTM.

@rjamet, you can see the rendered output with the folloing commands:

```
grunt package   # May take a while :)
grunt webserver
```

The open http://localhost:8000/build/docs/.

(After you have run `grunt package` once, you can run `grunt docs` (to only update the docs) and reload your browser to see the changes.)

2017-03-15 14:31 UTC, rjamet commented
Your fears are justified, that parses paragraphs in param/return blocks as code blocks if there's an empty line. 

I'm tempted to keep the +4 indentation, and work around this by either two spaces + simple line break (=`<br/>` in markdown), or `</p><p>`. Would that be fine? It lets us be consistent, even if it's not that pretty: the issue is then to know if anything else consumes this. BR loses paragraphs, paragraphs add markup that might not make sense in IDEs. 

I spotted a few unrelated issues otherwise, I'll bundle them as part of the next fix.

2017-03-20 14:23 UTC, gkalpak commented
Either way works for me, as long as the output looks the way it should.

2017-03-21 13:56 UTC, rjamet commented
Ok, fixed:
- capitalization of the return sections 
- some sce/scedelegate uniformization between getTrusted parameters 
- one "js" that should have been `$sce.JS`
- default values for the resource url white/blacklists should be described in description, not in return 
- +4 indentation everywhere it makes sense, `</p><p>` to keep paragraphs in there, except on the parseAs functions where I kept the +3 because +4-indented lists resist any dirty hack I could find :/

I checked all the $sce doc output, it should be the same where I didn't change the text.

2017-03-21 14:39 UTC, gkalpak approved these changes
I trust you that it looks good when rendered :smiley:
(You still need to fix the linting issue Travis complains about.)

2017-03-21 14:51 UTC, rjamet commented
Oops, sorry, I missed it. Fixed.

2017-03-21 15:36 UTC, closed without merging