docs(ngAnimate): Improve Staggering config for animations
angular/angular.js pull request #15743
Opened 2017-02-23 09:59 UTC by huggaf

After console.log the output from the computeCachedCssStaggerStyles function I realized that I need set animation-duration to 0s and animation-delay on my stagger class as I am using animations instead of transitions.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-02-23 10:04 UTC, huggaf commented
I signed it!

2017-03-02 11:06 UTC, Narretz requested changes
Just white-space changes

2017-03-02 11:06 UTC, Narretz commented on src/ngAnimate/module.js
> + *   /&#42; if you are using animations instead of transitions you should configure as follows:
Please remove the trailing whitespace in this line

2017-03-02 11:06 UTC, Narretz commented on src/ngAnimate/module.js
> + *     animation-delay: 0.1s;
Please remove the trailing whitespace in this line

2017-03-07 19:21 UTC, closed without merging