docs(guide/Migrating from Previous Versions): add info for 1.4 ngPatt…
angular/angular.js pull request #15765
Opened 2017-03-01 09:54 UTC by diegomrsantos

…ern and pattern breaking change

Introduced in commit 0e00108

Closes #15758

2017-03-01 09:56 UTC, diegomrsantos commented
I signed it!

2017-03-01 18:57 UTC, Narretz requested changes

2017-03-01 18:57 UTC, Narretz commented on docs/content/guide/migration.ngdoc
> +against the `viewValue` of `ngModel`, i.e. the value of the model
You should prefix viewValue, modelValue with `$` as this is how they are stored in the model

2017-03-01 18:58 UTC, Narretz commented
Can you add a note to the commit message that the content in the migration guide is taken from the commit message of 0e00108?

2017-03-07 19:10 UTC, Narretz approved these changes

2017-03-07 19:13 UTC, merged