docs ($compile): add error documentation for noslot error in $compile
angular/angular.js pull request #15828
Opened 2017-03-17 14:22 UTC by JoshuaJWilborn

there was no error page for the $compile:noslot error

this resolves #15790

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-03-17 14:22 UTC, JoshuaJWilborn commented
It says that I need CLA but I've already filled one out.

2017-03-17 14:36 UTC, JoshuaJWilborn commented
I checked and it was because my git signature was for my work email. I've added my work email as an alternate email to my google account, how do I get the CLA bot to rerun the check? Thanks.

2017-03-20 18:27 UTC, JoshuaJWilborn commented
Is there anything else I need to do/update etc to get this merged? :)

2017-03-21 12:23 UTC, Narretz commented
I will review the PR this week

2017-03-21 15:41 UTC, Narretz requested changes
Looking good generally, just a few things to improve / move around

2017-03-21 15:41 UTC, Narretz commented on docs/content/error/$compile/noslot.ngdoc
> +\\ if we the following change we will no longer get no slot error.
If we make ...

2017-03-22 10:51 UTC, merged

2017-03-22 10:53 UTC, Narretz commented
Thanks @JoshuaJWilborn - for future PRs, additional commits with adjustments don't have to have a "perfect commit message" because we will squash them into one in the end. It's also a good idea to create a new branch for each PR.