docs(filter): clarify the comparator parameter
angular/angular.js pull request #15827
Opened 2017-03-17 11:56 UTC by fcostarodrigo

The previous description does not make it clear how this parameter is used with other parameters
and its purpose.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

This is a doc update.

**What is the current behavior? (You can also link to an open issue here)**

N/A

**What is the new behavior (if this is a feature change)?**

N/A

**Does this PR introduce a breaking change?**

This PR does not introduce a breaking change.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-03-17 12:01 UTC, fcostarodrigo commented
I signed it!

2017-03-20 12:10 UTC, gkalpak requested changes

2017-03-20 12:10 UTC, gkalpak commented on src/ng/filter/filter.js
> + *     actual value from the array is equal to the expected value from the filter expression.
TBH, I feel this change is more confusing. E.g. `comparator` is **not** used to _"further refine the search results"_.  And _"should be used"_ sounds more like the user should do something (vs AngularJS using the function under the hood). And also `actual` is not necessarily a _"value from the array"_, but can be a property or sub-property of an item in the collection/array.

2017-03-22 13:11 UTC, gkalpak commented on src/ng/filter/filter.js
> + *     determining if matches returned by the argument expression should be considered a match based
The matches are not _returned_ by the `expression` argument. How about something like:

> determining if values retrieved using `expression` should be...

2017-03-23 14:52 UTC, closed without merging