docs(faq): clarify the versioning strategy
angular/angular.js pull request #15845
Opened 2017-03-22 11:11 UTC by Narretz

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Docs

**What is the current behavior? (You can also link to an open issue here)**
Information is not super clear

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:
clarify info on:
- When do features and breaking changes appear
- Relationship with Semver
- Compatibility of core and optional modules

2017-03-22 11:18 UTC, mgol requested changes

2017-03-22 11:18 UTC, mgol commented on docs/content/misc/faq.ngdoc
> +}
Maybe add another example where versions are really locked as well?

2017-03-22 11:24 UTC, Narretz commented on docs/content/misc/faq.ngdoc
> +}
You mean locked down to the patch version without ~?

2017-03-22 11:25 UTC, gkalpak commented on docs/content/misc/faq.ngdoc
> +developer experience (especially with regard to updating to Angular).
_updating_ --> _upgrading_ (?)

2017-03-22 11:25 UTC, gkalpak commented on docs/content/misc/faq.ngdoc
> +down the patch number, otherwise your application might break.
_down the_ --> _down to the_ (?)

2017-03-22 11:25 UTC, gkalpak commented on docs/content/misc/faq.ngdoc
> +When adding new code to branches of AngularJS, have a very stringent commit policy:
Not sure what "branches" refers to :grin: _Update: I get it now (after reading further below), but people won't know._
Also: _have_ --> _we have_ (?)

2017-03-22 11:25 UTC, gkalpak commented on docs/content/misc/faq.ngdoc
> +- Every commit must contain tests and documentation updates alongside the code changes and that all the
_and that all_ --> _and all_ (?)

2017-03-22 11:25 UTC, gkalpak commented on docs/content/misc/faq.ngdoc
> +for release notes.
Let's add a link to the commit message guidelines (or CONTRIBUTING.md).

2017-03-22 11:25 UTC, gkalpak commented on docs/content/misc/faq.ngdoc
> +not used at Google or without sufficient test coverage, have a chance of making it through.
I am not sure the last two paragraphs are super-relevant to external contributors.

2017-03-22 11:34 UTC, mgol commented on docs/content/misc/faq.ngdoc
> +}
Yes, to indicate that if you lock to a specific version, all versions need to be the same.

2017-03-24 09:46 UTC, Narretz commented on docs/content/misc/faq.ngdoc
> +not used at Google or without sufficient test coverage, have a chance of making it through.
I assume they are meant to inspire confidence in the stability of AngularJS (I've just reworded them from their previous state)

2017-03-24 09:53 UTC, gkalpak commented on docs/content/misc/faq.ngdoc
> +not used at Google or without sufficient test coverage, have a chance of making it through.
I didn't notice they were there before :confused: Fair enough.
👍 on rewording.

2017-03-24 10:00 UTC, Narretz commented
Updated, PTAL

2017-03-24 10:42 UTC, gkalpak approved these changes
A couple of typos. LGTM otherwise.

2017-03-24 10:42 UTC, gkalpak commented on docs/content/misc/faq.ngdoc
>  - Every commit must contain tests and documentation updates alongside the code changes and that all the
_and that all_ --> _and all_ (or is it intentional?)

2017-03-24 10:42 UTC, gkalpak commented on docs/content/misc/faq.ngdoc
> +Firefox, Safari, and Safari for iOs, Edge, as well as Internet Explorer versions 9-11. See
_iOs_ --> _iOS_

(Are we running against Edge yet?)

2017-03-24 11:14 UTC, mgol commented on docs/content/misc/faq.ngdoc
> +Firefox, Safari, and Safari for iOs, Edge, as well as Internet Explorer versions 9-11. See
We're not: issue #13687, PR #14401.

Yes, we should fix that. :D

2017-03-24 11:15 UTC, mgol approved these changes

2017-03-24 11:31 UTC, Narretz commented on docs/content/misc/faq.ngdoc
> +Firefox, Safari, and Safari for iOs, Edge, as well as Internet Explorer versions 9-11. See
I removed it again. Edge had some problems with the script security checks last time i checked

2017-03-24 11:45 UTC, merged

2017-03-24 11:45 UTC, Narretz commented
Thanks for the reviews!