provide isError and use it in place of instanceof Error
angular/angular.js pull request #15872
Opened 2017-03-30 08:54 UTC by graingert

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature/bug

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

Angular should pass them on to the correct excetion handler, and there's an angular.isError function now.

**Does this PR introduce a breaking change?**

No

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

re-implimented https://github.com/yefremov/iserror/blob/master/index.js to avoid license and make code faster.

Fixes #15868

2017-03-30 14:56 UTC, graingert commented
@gkalpak what would be a good way to construct a test that boots up an iframe? And where should I put it?

```js
function testError(createError) {
    var iframe = document.createElement('iframe');
    document.body.appendChild(iframe);
    try {
        var error = createError(contentWindow);
        expect(error instanceof Error).to.be.false();
        expect(isError(error)).to.be.true();
    } finally {
        iframe.parentElement.removeChild(iframe);
    }
}

testError(function (win) {
    return new win.Error();
});

testError(function (win) {
    try {
        win.document.querySelectorAll('');
    catch(e) {
        return e;
    }
});
```

2017-03-30 15:00 UTC, gkalpak reviewed
A couple of minor comments. Looks OK otherwise (except for the missing tests).
The tests can go in https://github.com/graingert/angular.js/blob/af80f4765e2a9e795f64103b6e15770cf6eda050/test/AngularSpec.js.

2017-03-30 15:00 UTC, gkalpak commented on src/Angular.js
> + * @name angular.isError
I don't think we want to make this public.

2017-03-30 15:00 UTC, gkalpak commented on src/Angular.js
> +  var tag = ({}).toString.call(value);
We already have a closure-global `toString = Object.prototype.toString`. You can simply `toString.call(value)`.

2017-03-30 15:00 UTC, gkalpak commented on test/minErrSpec.js
> +    expect(isError(myError)).toBe(true);
This seems irrelevant here. Please remove.

2017-03-30 15:03 UTC, graingert commented
What's wrong with publishing it?

On 30 Mar 2017 16:02, "George Kalpakas" <notifications@github.com> wrote:

> *@gkalpak* commented on this pull request.
>
> A couple of minor comments. Looks OK otherwise (except for the missing
> tests).
> The tests can go in https://github.com/graingert/angular.js/blob/
> af80f4765e2a9e795f64103b6e15770cf6eda050/test/AngularSpec.js.
> ------------------------------
>
> In src/Angular.js
> <https://github.com/angular/angular.js/pull/15872#discussion_r108948131>:
>
> > @@ -675,6 +676,28 @@ var isArray = Array.isArray;
>
>  /**
>   * @ngdoc function
> + * @name angular.isError
>
> I don't think we want to make this public.
> ------------------------------
>
> In src/Angular.js
> <https://github.com/angular/angular.js/pull/15872#discussion_r108948760>:
>
> > @@ -675,6 +676,28 @@ var isArray = Array.isArray;
>
>  /**
>   * @ngdoc function
> + * @name angular.isError
> + * @module ng
> + * @kind function
> + *
> + * @description
> + * Determines if a reference is an `Error`.
> + *
> + * @param {*} value Reference to check.
> + * @returns {boolean} True if `value` is an `Error`.
> + */
> +function isError(value) {
> +  var tag = ({}).toString.call(value);
>
> We already have a closure-global toString = Object.prototype.toString.
> You can simply toString.call(value).
> ------------------------------
>
> In test/minErrSpec.js
> <https://github.com/angular/angular.js/pull/15872#discussion_r108949130>:
>
> > @@ -17,6 +17,7 @@ describe('minErr', function() {
>    it('should return an Error factory', function() {
>      var myError = testError('test', 'Oops');
>      expect(myError instanceof Error).toBe(true);
> +    expect(isError(myError)).toBe(true);
>
> This seems irrelevant here. Please remove.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular.js/pull/15872#pullrequestreview-30016050>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAZQTITCKX7C5KczFgrrgsjIyNF_59gJks5rq8PvgaJpZM4MuDhG>
> .
>

2017-03-30 15:11 UTC, gkalpak commented
> What's wrong with publishing it?

We have to maintain it in a backwards compatible way. If it is not public we can change/improve/remove it without any concerns.

2017-03-30 15:22 UTC, graingert commented
How do you not publish it?

On 30 Mar 2017 16:12, "George Kalpakas" <notifications@github.com> wrote:

> What's wrong with publishing it?
>
> We have to maintain it in a backwards compatible way. If it is not public
> we can change/improve/remove it without any concerns.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular.js/pull/15872#issuecomment-290441957>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAZQTBBUqkJGm3d_0jwZXROJIntlmhH7ks5rq8Z6gaJpZM4MuDhG>
> .
>

2017-03-30 15:54 UTC, gkalpak commented
> How do you not publish it?

Remove the `@ngdoc` anotation (and others that are not relevant/necessary: `@name`, `@module ng`, `@kind`).
(It won't be available anyway, so we don't want to have it appear on the docs either.)

2017-03-30 16:03 UTC, graingert commented on src/ngMock/angular-mocks.js
> +      } else if (angular.isError(object)) {
a publishes isError is required here.

2017-03-31 07:31 UTC, gkalpak requested changes

2017-03-31 07:31 UTC, gkalpak commented on test/AngularSpec.js
> +    function testError(createError) {
Move this either at the top or at the bottom of the `describe` block (or even create a nested `describe` for "other-context" tests) and give it a more descriptive name (e.g. `testErrorFromDifferent context`.

Maybe having a separate `describe` block with `beforeAll`/`afterAll` blocks for creating/destorying the iframe is a good idea.

2017-03-31 07:31 UTC, gkalpak commented on src/ngMock/angular-mocks.js
> +      } else if (angular.isError(object)) {
We could make it "private API" (e.g. `angular.$$isError`), but I don't think it is worth it. This function (`angular.mock.dump`) is very rarely used. It is also very rare to have new window contexts in unit tests and it is even more rare to have them throw errors. Plus, `DOMException`s get decently stringified by `JSON.stringify` (in contrast to plain `Error`s which become `"{}"`). All that considered, I think this one occurrence can remain `object instanceof Error` :smiley:

2017-03-31 09:08 UTC, graingert commented on test/AngularSpec.js
> +    function testError(createError) {
try { } finally { } is more fine grained in this usecase

2017-03-31 09:23 UTC, gkalpak commented on test/AngularSpec.js
> +    function testError(createError) {
What do you mean?

2017-03-31 09:39 UTC, graingert commented on test/AngularSpec.js
> +    function testError(createError) {
it's specific to the actual call to the testErrorFromDifferentContext function. Like the lifetime of the iframe is shorter than a test, no point leaving it hanging around until afterAll/beforeAll is called.

2017-04-01 01:00 UTC, gkalpak commented on test/AngularSpec.js
> +    function testError(createError) {
I am fine either way, so feel free to leave things as they are :smiley:

2017-04-03 10:16 UTC, graingert commented on test/AngularSpec.js
> +    function testError(createError) {
ok

2017-04-03 10:19 UTC, graingert commented
@gkalpak ok, I'm pretty I've resolved anything.  Interestingly enough if seems as though Safari thinks DOMExceptions from frames are instances of Errors

2017-04-27 12:52 UTC, gkalpak approved these changes
LGTM

2017-04-27 12:52 UTC, gkalpak commented on test/AngularSpec.js
> +        .toBe(false);
Nit: Unnecessarily wrapped line.

2017-04-27 12:54 UTC, gkalpak commented
(The commit message needs some love (as it doesn't follow [our guidelines][1]).)

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit

2017-04-27 12:58 UTC, petebacondarwin approved these changes

2017-04-27 13:01 UTC, graingert commented
I'd like to add DOMError too

On 27 Apr 2017 2:00 pm, "Pete Bacon Darwin" <notifications@github.com>
wrote:

> *@petebacondarwin* approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular.js/pull/15872#pullrequestreview-35097520>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAZQTKZoRTmedGNuh_8wmQHTtito9d72ks5r0JFQgaJpZM4MuDhG>
> .
>

2017-04-27 13:17 UTC, gkalpak commented
I am going to merge this as is, but feel free to add `DOMError` in another PR :grin:

2017-04-27 13:26 UTC, graingert commented
<del>I'd like to add DOMError too</del>

scratch that, DOMError only has a 'name' property and never has a stack, so it shouldn't be added imhop.

2017-04-27 14:13 UTC, gkalpak commented
Actually, before I merge it can you take care of the following:
1. Fix https://github.com/angular/angular.js/pull/15872#discussion_r113686119.
2. Fix the commit message to follow the commit message guidelines.
3. Add a comment above the function pointing to the original project.

2017-04-27 14:18 UTC, graingert commented
> Fix the commit message to follow the commit message guidelines.

what message should I use?

2017-04-27 15:11 UTC, gkalpak commented
Something that follows [the guidelines][1]. E.g. something like:

> fix(*): correctly detect Error instances from different contexts 
>
> 12345678901234567890123456789012345678901234567890123456789012345678901234567890
> Errors thrown from different contexts (such as an iframe or webworker) are not detected as Error
> instances and handled accordingly.
> This commit fixes it by introducing an `isError()` helper, that is able to correctly detect such
> instances.
> 
> Fixes #15868 

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit

2017-05-22 10:30 UTC, graingert commented
@gkalpak any updates on this?

2017-05-22 11:10 UTC, closed without merging