docs(uppercase): Added an example
angular/angular.js pull request #15885
Opened 2017-04-03 19:49 UTC by snood1205

I saw that the uppercase filter had no example so I decided to add a minimal example to explain how the uppercase filter works.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Docs update.

**What is the current behavior? (You can also link to an open issue here)**
There is currently no example for the `uppercase` filter, so I added one.

**What is the new behavior (if this is a feature change)?**
N/a

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-04-05 10:47 UTC, Narretz commented
Thanks for the PR! Can you please make these 2 changes:
- remove the protractor test (it's a very simple test, and we run these tests for every build, so it adds up)
- add a link to the uppercase filter that you can find an example in the lowercase filter docs?

2017-04-05 11:55 UTC, snood1205 commented
I remove the protractor file and added `@see angular.uppercase` to the docs for `lowercase`.

2017-04-05 23:21 UTC, snood1205 commented
@Narretz is this appropriate on the whole or would you like me to change this?

2017-04-07 13:14 UTC, Narretz requested changes

2017-04-07 13:14 UTC, Narretz commented on src/ng/filter/filters.js
> +   <example name="filter-uppercase">
you must add `module=uppercaseFilterExample`, otherwise the example won't work

2017-04-07 13:14 UTC, Narretz commented on src/ng/filter/filters.js
> + * @see angular.uppercase
The docs don't actually do anything with `@see` :(, please revert this change

2017-04-07 13:14 UTC, Narretz commented on src/ng/filter/filters.js
>   * Converts string to lowercase.
Please add a link after this that points to uppercase: Format is `{@link ng.filter.uppercase linktext}`

2017-04-07 15:17 UTC, Narretz commented
Thanks - I fixed the link myself because I gave you the wrong path ;)

2017-04-07 15:23 UTC, merged