docs(currency): Add sample of currency from scope
angular/angular.js pull request #15942
Opened 2017-04-27 08:50 UTC by j3hyde

docs(currency): Add sample of currency from scope

Added a sample line showing the use of a scope variable to set currency symbol.  E.g. for central i18n configuration.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This adds a docs update (example code).

**What is the current behavior? (You can also link to an open issue here)**
Shows currency symbols pulled from text strings.

**What is the new behavior (if this is a feature change)?**
Shows currency symbol pulled from scope.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [*] Tests for the changes have been added (for bug fixes / features)
- [*] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-04-27 10:22 UTC, gkalpak requested changes
Other than the failing tests it LGTM.
(BTW, you can run the tests locally with `grunt test`.)

2017-04-27 10:22 UTC, gkalpak commented on src/ng/filter/filters.js
> +         expect(element(by.id('currency-from-scope')).getText()).toBe('GBP£1,235.56');
This should be `1,234.56` (not `1,235.56`).

2017-04-27 10:22 UTC, gkalpak commented on src/ng/filter/filters.js
> +         expect(element(by.id('currency-from-scope')).getText()).toBe('-GBP£1,234');
This should be `1,234.00` (not `1,234`).

2017-06-29 16:22 UTC, Narretz commented
@j3hyde are you still interested in making these changes?

2017-07-05 07:26 UTC, Narretz commented
I'm going to close this PR because we cannot merge it in its current state, as we are either waiting for more information, tests are missing, or required code changes haven't been made. 
Feel free to reopen this PR or open a new one if you have remdied the issues pointed out.

2017-07-05 07:26 UTC, closed without merging