test(support): verify support tests results in all tested browsers
angular/angular.js pull request #16008
Opened 2017-05-24 13:04 UTC by mgol

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

New tests.

**What is the current behavior? (You can also link to an open issue here)**

It's not tested whether browsers pass or fail specific support tests used to skip particular test blocks.

**What is the new behavior (if this is a feature change)?**

All browsers have verified support tests results.

**Does this PR introduce a breaking change?**

No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- ~~Docs have been added / updated (for bug fixes / features)~~

**Other information**:

2017-05-24 15:31 UTC, gkalpak requested changes

2017-05-24 15:31 UTC, gkalpak commented on test/ng/supportSpec.js
> +'use strict';
I would expect this file to be in `test/helpers/`. Why here? It is confusing.

2017-05-24 15:31 UTC, gkalpak commented on test/ng/supportSpec.js
> +    // i.e. the macOS version in place of the iOS version so they'd fall into an incorrect bucket.
Missing closing `)`.

2017-05-24 15:31 UTC, gkalpak commented on test/ng/supportSpec.js
> +    userAgent = userAgent.replace(/iPhone OS 10(?:_\d)+/, 'iPhone OS 8_1');
`_\d` --> `_\d+`

2017-05-24 15:31 UTC, gkalpak commented on test/ng/supportSpec.js
> +  if (/edge\//i.test(userAgent)) {
Why not convert `userAgent` to lowercase once and avoid all the `i` flags? :smiley:

2017-05-24 15:31 UTC, gkalpak commented on test/ng/supportSpec.js
> +  } else if (/(?:msie|trident)/i.test(userAgent)) {
`/(?:msie|trident)/` --> `/msie|trident/`

2017-05-24 15:31 UTC, gkalpak commented on test/ng/supportSpec.js
> +  } else if (/\b9\.\d+(\.\d+)* safari/i.test(userAgent)) {
`/\b9\.\d+(\.\d+)*` --> `/\b9(?:\.\d+)+`

2017-05-24 15:31 UTC, gkalpak commented on test/ng/supportSpec.js
> +  } else if (/\b\d+\.\d+(\.\d+)* safari/i.test(userAgent)) {
`/\b\d+\.\d+(\.\d+)*` --> `/\b\d+(?:\.\d+)+`

2017-05-24 15:31 UTC, gkalpak commented on test/ng/supportSpec.js
> +  } else if (/android 4\.[0-3]/i.test(userAgent)) {
This will break when Android 4.10 is out :stuck_out_tongue:

2017-05-24 15:43 UTC, mgol commented on test/ng/supportSpec.js
> +'use strict';
That was my plan. I must have clicked the wrong directory. ;)

2017-05-24 15:44 UTC, mgol commented on test/ng/supportSpec.js
> +  } else if (/android 4\.[0-3]/i.test(userAgent)) {
Android 4.x is dead, we're safe. :)

2017-05-24 15:45 UTC, mgol commented on test/ng/supportSpec.js
> +'use strict';
Why in `test/helpers`? `test/helpers/` contains helpers for tests, not actual tests.

2017-05-24 15:47 UTC, mgol commented on test/ng/supportSpec.js
> +  if (/edge\//i.test(userAgent)) {
That would have to be `lowerCasedUserAgent` to be precise. And maybe we'll need case sensitivity one day?

2017-05-24 16:07 UTC, gkalpak commented on test/ng/supportSpec.js
> +'use strict';
It contains helpers for tests and their tests (when they exist) :smiley:
For lack of a better directory, keeping the pec file next to the source is better than putting it into an arbitrary directory 😛

2017-05-24 18:49 UTC, mgol commented
@gkalpak PR updated, tests now pass.

2017-05-24 19:50 UTC, gkalpak commented
Why did tests previously fail?
LGTM except for `supportSpec` being in `test/ng/` (instead of `test/helpers/`), as is [privateMocksSpec.js][1] for example.

[1]: https://github.com/mgol/angular.js/blob/492cb3537522da51ed6ea0f8895fc929ff8add17/test/helpers/privateMocksSpec.js

2017-05-25 07:32 UTC, mgol commented
The spec file moved (I missed `privateMocksSpec.js` previously).

The tests were failing as I didn't add results for Safari 8 so it was treated the same as Safari 10. :-)

2017-05-25 12:51 UTC, gkalpak approved these changes

2017-05-25 14:14 UTC, merged