feature($resource): Add Resource To Response For Error Interceptors
angular/angular.js pull request #16109
Opened 2017-07-13 17:52 UTC by kmccullough

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Similar to how the resource object (which is to be populated later) is added to the response for a successful request and accessible to the response interceptor, this change attaches the resource object to the response for a failed request and is accessible by the responseError interceptor.

**What is the current behavior? (You can also link to an open issue here)**
The resource object is not accessible from the responseError interceptor.

**What is the new behavior (if this is a feature change)?**
The resource object is accessible from the responseError interceptor.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-07-13 19:40 UTC, kmccullough commented
test this please

2017-07-14 10:50 UTC, gkalpak requested changes
Could you please add some docs for that. I think the behavior of adding `resource` to the response is not documented (and it should be).
<sub>(If you don't feel like adding the docs, it's OK :smiley:)</sub>

LGTM otherwise 👍

2017-07-14 18:02 UTC, kmccullough commented
@gkalpak How's that?

2017-07-18 13:48 UTC, gkalpak approved these changes

2017-07-18 14:11 UTC, closed without merging