chore(docs-app): load example files based on active deployment
angular/angular.js pull request #16120
Opened 2017-07-18 14:11 UTC by Narretz

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
load the example files in the docs app based on the current deployment

I'm getting these warnings in dgeni with my changes: 

```
warn:    No getAlias(doc) method provided - doc "deployment-data-debug" (deployment-data)
warn:    No getAlias(doc) method provided - doc "deployment-data-default" (deployment-data)
warn:    No getAlias(doc) method provided - doc "deployment-data-jquery" (deployment-data)
warn:    No getAlias(doc) method provided - doc "deployment-data-production" (deployment-data)

warn:    No path template provided - doc "deployment-data-debug" (deployment-data)
warn:    No path template provided - doc "deployment-data-default" (deployment-data)
warn:    No path template provided - doc "deployment-data-jquery" (deployment-data)
warn:    No path template provided - doc "deployment-data-production" (deployment-data)
```

2017-07-25 14:08 UTC, gkalpak requested changes
Unfortunately, there is no way to actually test this, but it mostly LGTM (with Travis issues fixed).

2017-07-25 14:08 UTC, gkalpak commented on scripts/code.angularjs.org-firebase/functions/index.js
> +        const dirName = directoryPath.split('/').reverse()[1];
:smiley:

2017-07-25 14:08 UTC, gkalpak commented on scripts/code.angularjs.org-firebase/functions/index.js
> +        const fileName = file.metadata.name.split('/').reverse()[0];
Or: `file.metadata.name.split('/').pop()`

2017-07-25 14:08 UTC, gkalpak commented on scripts/code.angularjs.org-firebase/functions/index.js
> +        if (files.length === 0 && (apiResponse && !apiResponse.prefixes || !apiResponse)) {
Or: `if (!files.length && (!apiResponse || !apiResponse.prefixes)`

2017-07-26 18:03 UTC, Narretz commented on docs/config/templates/examples/runnableExample.template.html
> +    <iframe class="runnable-example-frame" ng-src="{{getExampleIndex('{$ doc.example.deployments.default.path $}', deployment)}}" name="{$ doc.example.id $}"></iframe>
Can't tell if you're joking ;) ngSrc takes interpolation :/

2017-07-26 18:11 UTC, gkalpak commented on docs/config/templates/examples/runnableExample.template.html
> +    <iframe class="runnable-example-frame" ng-src="{{getExampleIndex('{$ doc.example.deployments.default.path $}', deployment)}}" name="{$ doc.example.id $}"></iframe>
OMG! Confused by Angular's `[src]`. That's embarassing 😳
The second comment is still valid (hopefully) :grin:

2017-07-26 18:16 UTC, Narretz commented
Second one is fixed ;)

George Kalpakas <notifications@github.com> schrieb am Mi., 26. Juli 2017
20:13:

> *@gkalpak* commented on this pull request.
> ------------------------------
>
> In docs/config/templates/examples/runnableExample.template.html
> <https://github.com/angular/angular.js/pull/16120#discussion_r129653065>:
>
> > @@ -18,7 +18,7 @@
>      </div>
>    {% endfor %}
>
> -    <iframe class="runnable-example-frame" src="{$ doc.example.deployments.default.outputPath $}" name="{$ doc.example.id $}"></iframe>
> +    <iframe class="runnable-example-frame" ng-src="{{getExampleIndex('{$ doc.example.deployments.default.path $}', deployment)}}" name="{$ doc.example.id $}"></iframe>
>
> OMG! Confused by Angular's [src]. That's embarassing 😳
> The second comment is still valid (hopefully) 😁
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular.js/pull/16120#discussion_r129653065>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABGYSUYH7j0ryP6jUWf0sLu9WWT0HeP7ks5sR4HGgaJpZM4ObaBH>
> .
>

2017-07-31 09:10 UTC, Narretz commented
Is this okay now @gkalpak ?

2017-07-31 11:45 UTC, gkalpak approved these changes

2017-07-31 11:45 UTC, gkalpak commented
I think so :smiley:

2017-07-31 13:58 UTC, merged