fix($http): add check for functions in request
angular/angular.js pull request #16133
Opened 2017-07-27 13:10 UTC by carlfranz

Avoid that functions in `params` object (like getter or setter) will be encoded in the url.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix.

**What is the current behavior? (You can also link to an open issue here)**
 Functions in class-object are encoded in url.

**What is the new behavior (if this is a feature change)?**
 Functions in class-object are no more encoded in url

**Does this PR introduce a breaking change?**
no

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:
See example of bug here: https://embed.plnkr.co/tspyPWVcm6jMpVDBl6WK/ (open console)

2017-07-27 13:20 UTC, carlfranz commented
I signed it!

2017-07-28 09:22 UTC, gkalpak requested changes
The change looks reasonable. Thx 👍
We need:

1. Tests
2. To decide whether it is a breaking change or not.

2017-07-28 18:48 UTC, carlfranz commented
shows me an error on ng-model O_o

2017-07-29 22:46 UTC, gkalpak requested changes
Not directly related to this PR, but I realized that `$httpParamSerializerJQLike` treats functions differently than jQuery (jQuery calls functions and uses the return value).

2017-07-29 22:46 UTC, gkalpak commented on test/ng/httpSpec.js
> +    });
This is not common functionality. It does not belong here, but in `default array serialization` section.

2017-07-31 08:03 UTC, gkalpak commented
@carlfranz, feel free to ping me when this is ready for another review.

2017-07-31 08:07 UTC, carlfranz commented on test/ng/httpSpec.js
> +    });
moved!

2017-07-31 11:00 UTC, carlfranz commented
ping? :)

2017-07-31 11:29 UTC, gkalpak approved these changes

2017-07-31 13:16 UTC, closed without merging