Update http.js
angular/angular.js pull request #16132
Opened 2017-07-27 09:44 UTC by carlfranz

Avoid that functions in `params` object (like getter or setter) will be encoded in the url.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix.

**What is the current behavior? (You can also link to an open issue here)**
 Functions in class-object are encoded in url.

**What is the new behavior (if this is a feature change)?**
 Functions in class-object are no more encoded in url

**Does this PR introduce a breaking change?**
no

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-07-27 10:10 UTC, gkalpak requested changes
This looks reasonable. (TBD if it is a breaking change or not.)
Could you add some tests?

2017-07-27 10:10 UTC, gkalpak commented on src/ng/http.js
> +        if (typeof value === 'function') return;
You can incorporate with the previous line:

```js
if (value === null || isUndefined(value) || isFunction(value)) return;
```

2017-07-27 12:15 UTC, carlfranz commented on src/ng/http.js
> +        if (typeof value === 'function') return;
done! Can't find how to rename wrong commit :(

2017-07-27 13:07 UTC, closed without merging

2017-07-27 17:25 UTC, carlfranz commented
I created new one with the right commit format at https://github.com/angular/angular.js/pull/16133 please delete this. :+1:

2017-07-28 09:21 UTC, gkalpak commented on src/ng/http.js
> +        if (typeof value === 'function') return;
@carlfranz, you can amend your last commit with `git commit --amend`.
(Or if you want to change/reorganize multiple commits, `git rebase --interactive <COMMIT_RANGE>` is powerful tool. Too powerful - ue at your own risk 😛)