docs($http): update YQL currency exchange API example
angular/angular.js pull request #16137
Opened 2017-07-30 16:59 UTC by andypotts

Closes #16130

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
docs update

**What is the current behavior? (You can also link to an open issue here)**
Currently, the example uses YQL to fetch currency exchange rates (#16130)

**What is the new behavior (if this is a feature change)?**
I have updated the example to a simpler solution that uses the Fixer.io API.  

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-07-31 07:59 UTC, gkalpak requested changes
A couple of nits. LGTM otherwise.
:100: for simplifying the example.

2017-07-31 07:59 UTC, gkalpak commented on docs/content/guide/concepts.ngdoc
> +from the web, e.g. by calling the Fixer.io exchange rate API, without changing the controller.
Make `Fixer.io` a link.

2017-07-31 07:59 UTC, gkalpak commented on docs/content/guide/concepts.ngdoc
> +Let's finish our example by fetching the exchange rates from the Fixer.io exchange rate API.
Make `Fixer.io` a link.

2017-07-31 07:59 UTC, gkalpak commented on docs/content/guide/security.ngdoc
> +Bear in mind that calling `$http.jsonp`, like in [our currency exchange example](https://docs.angularjs.org/guide/concepts#accessing-the-backend),
Actually, this `line in...` clause is obsolete. We no longer use `jsonp` in that example for quite some time.
Please remove that part.

2017-07-31 08:01 UTC, gkalpak commented
You know what would be awesome (not necessarily in this PR)?
Adding some end-to-end tests for that example :grin:

2017-07-31 12:25 UTC, andypotts commented
@gkalpak I've fixed those issues, and agree that some end-to-end tests would be good. When I get a chance I'll create another PR 😄

2017-07-31 13:08 UTC, gkalpak requested changes

2017-07-31 13:08 UTC, gkalpak commented on docs/content/guide/concepts.ngdoc
> +from the web, e.g. by calling the <a href="http://fixer.io" title="fixer" target="_blank">Fixer.io</a> exchange rate API, without changing the controller.
`.ngdoc` files understand markdown. You can use `[Fixer.io](http://fixer.io)` for brevity.

2017-07-31 13:08 UTC, gkalpak commented on docs/content/guide/security.ngdoc
> +Bear in mind that calling `$http.jsonp`,
Remove the `,`. It is not necessary any more.

2017-07-31 19:01 UTC, andypotts commented
@gkalpak thanks, hopefully it's good to go now!

2017-08-01 08:57 UTC, gkalpak approved these changes

2017-08-02 10:34 UTC, closed without merging