fix($httpParamSerializerJQLike): call functions as jQuery does
angular/angular.js pull request #16139
Opened 2017-07-31 18:09 UTC by frederikprijck

Closes #16138

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix

**What is the current behavior? (You can also link to an open issue here)**
Previously, `httpParamSerializerJQLike` did not handle properties of type function.

**What is the new behavior (if this is a feature change)?**
This commit ensures function properties are executed and the return value is used.

**Does this PR introduce a breaking change?**
See: https://github.com/angular/angular.js/issues/16138#issuecomment-319066731

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2017-08-01 09:23 UTC, gkalpak requested changes
There are no tests with functions inside arrays 😞 

Can you also change the commit message to make it more clear that previously function were stringified (not ignored). This will make it easier for people understand what differences to expect.

2017-08-01 09:23 UTC, gkalpak commented on src/ng/http.js
> +          if (isFunction(toSerialize)) {
Merge with the `else` above for consistency:

```js
  ...
} else if (isFunction(toSerialize)) {
  ...
} else {
  ...
}
```

2017-08-01 09:23 UTC, gkalpak commented on test/ng/httpSpec.js
> +    });
These two tests are testing more (independent) things than necessary. They should focus on the `function` part. The rest is irrelevant.

2017-08-01 09:23 UTC, gkalpak commented on test/ng/httpSpec.js
> +    it('should serialize nested objects with function properties returning an object by repeating param name with [key] suffix', function() {
👍

2017-08-01 09:33 UTC, gkalpak commented on src/ng/http.js
> +            serialize(toSerialize(), prefix);
Actually, this is not how jQuery does it. They do not recursively serialize a returned object. They just [use the returned value][1].

[1]: https://github.com/jquery/jquery/blob/a6b0705294d336ae2f63f7276de0da1195495363/src/serialize.js#L60-L69

2017-08-01 10:46 UTC, frederikprijck commented
Updated the PR, added a test for a function in an array aswell!

2017-08-02 09:21 UTC, gkalpak requested changes
Please add some test for array inside object (e.g. `{foo: {bar: [valueFn('baz')]}}`).

2017-08-02 09:21 UTC, gkalpak commented on src/ng/http.js
> +                (toSerialize == null ? '' : encodeUriQuery(serializeValue(toSerialize))));
Wrong indentation :grin:

2017-08-02 09:21 UTC, gkalpak commented on src/ng/http.js
> +                (toSerialize == null ? '' : encodeUriQuery(serializeValue(toSerialize))));
Actually, you can avoid code duplication with:

```js
  ...
} else {
  if (isFunction(toSerialize)) {
    toSerialize = toSerialize();
  }
  parts.push(encodeUriQuery(prefix) + '=' +
      (toSerialize == null ? '' : encodeUriQuery(serializeValue(toSerialize))));
}
```

2017-08-02 09:21 UTC, gkalpak commented on test/ng/httpSpec.js
> +      expect(jqrSer({foo:[function() { return 'bar'; }]})).toEqual('foo%5B%5D=bar');
Missing space after `:`. :grin:
BTW, you an probably use `valueFn('bar')` to save some typing 😎

2017-08-02 09:21 UTC, gkalpak commented on test/ng/httpSpec.js
> +        'a=b');
Remove the _"by repeating param name with [key] suffix"_ part, which is irrelevant (here and below).
Weird line-splitting (here and below) 😕

2017-08-02 09:21 UTC, gkalpak commented on test/ng/httpSpec.js
> +        //a={"b": "c"}
There is no space after `:`.

2017-08-02 09:21 UTC, gkalpak commented on test/ng/httpSpec.js
> +        'a=%7B%22b%22:%22c%22%7D');
This is not exactly how jQuery does it, but that is not related to this PR :grin:

2017-08-02 09:21 UTC, gkalpak commented on test/ng/httpSpec.js
> +        //foo[bar]={"bav": "barv"}
No space after `:`.

2017-08-02 09:21 UTC, gkalpak commented on test/ng/httpSpec.js
> +      expect(jqrSer({foo: {'bar': function() { return 'barv'; }}})).toEqual(
No need for quoting `bar` (here and below).

2017-08-02 10:29 UTC, frederikprijck commented
Updated!

2017-08-02 10:33 UTC, gkalpak requested changes

2017-08-02 10:33 UTC, gkalpak commented on src/ng/http.js
> +            (toSerialize == null ? '' : encodeUriQuery(serializeValue(toSerialize))));
Wrong indentation. 😞

2017-08-02 10:33 UTC, gkalpak commented on test/ng/httpSpec.js
>          'foo%5Bbar%5D=barv');
Weird line break (here and below) :confused:

2017-08-02 10:33 UTC, gkalpak commented on test/ng/httpSpec.js
> +      expect(jqrSer({foo: {bar: valueFn({ bav: 'barv' })}})).toEqual(
Inconsistent whitespace after `{` and before `}` :grin:

2017-08-03 09:39 UTC, gkalpak requested changes

2017-08-03 09:39 UTC, gkalpak commented on test/ng/httpSpec.js
> +      expect(jqrSer({foo: [valueFn('bar')]})).toEqual('foo%5B%5D=bar');
Where's the decoded comment (`foo[]=bar`)? :grin:

2017-08-03 09:39 UTC, gkalpak commented on test/ng/httpSpec.js
> +    it('should serialize objects with function properties returning an object by repeating param name with [key] suffix', function() {
Inaccurate description.

2017-08-03 09:39 UTC, gkalpak commented on test/ng/httpSpec.js
> +      expect(jqrSer({foo: {bar: valueFn({ bav: 'barv'})}})).toEqual('foo%5Bbar%5D=%7B%22bav%22:%22barv%22%7D'); //foo[bar]={"bav":"barv"}
Extra whitespace in `{ bav`. 😱

2017-08-03 17:56 UTC, gkalpak approved these changes

2017-08-03 18:03 UTC, closed without merging

2017-08-03 18:05 UTC, gkalpak commented
Merging to master only, since it has already deviated from 1.6.x (not converting empty strings to `null`).