docs($compileProvider): More information on debugInfoEnabled
angular/angular.js pull request #16154
Opened 2017-08-08 16:29 UTC by oBusk

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Improves documentation about what `$compileProvider.debugInfoEnabled(true)` does.

**Other information**:

Based on [compile.js](https://github.com/angular/angular.js/blob/b4d1e5e492df43c49c9e4215ea75d9155fd8ba88/src/ng/compile.js#L1819...L1851) source code.

Please feel free to improve the wording or come with feedback.

2017-08-08 20:05 UTC, gkalpak requested changes

2017-08-08 20:05 UTC, gkalpak commented on src/ng/compile.js
> +   * * `scope()` and `isolateScope()` allowing access to scope from DOM Element
It doesn't add the methods. The methods are always present. It adds the `$scope` or `$isolateScope` (or `$isolateScopeNoTemplate` data properties (that can be used by the `.scope()` and `.isolateScope()` methods).

2017-08-23 13:56 UTC, oBusk commented
@gkalpak I've ammended according to your comments. Thanks for the feedback.

2017-08-23 15:50 UTC, gkalpak requested changes

2017-08-23 15:50 UTC, gkalpak commented on src/ng/compile.js
> +   * * `$scope`, `$isolateScope` or `$isolateScopeNoTemplate` data properties which are accessable via the
This is too much implementation details imo. Please change to something like:

> Data properties used by the {@link angular.element#methods `scope()`/`isolateScope()` methods} to return the element's scope.

2017-08-23 16:04 UTC, oBusk commented on src/ng/compile.js
> +   * * `$scope`, `$isolateScope` or `$isolateScopeNoTemplate` data properties which are accessable via the
That is a very good point

2017-08-23 19:12 UTC, closed without merging