fix($compile): sanitize special chars in directive name
angular/angular.js pull request #16314
Opened 2017-11-01 13:31 UTC by curlydevil

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Fix for 

**What is the current behavior? (You can also link to an open issue here)**
In HTML markup only directive name's `x-` and `data-` prefixes are being sanitized. (#16278)

**What is the new behavior (if this is a feature change)?**
Also special chars are being sanitized, e.g. `<div _t></div>` will match `t` directive once again

**Does this PR introduce a breaking change?**
Should not

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:
@petebacondarwin suggested to update the regex, and I hope that I did it in a way he was thinking about it.

2017-11-01 15:32 UTC, Narretz commented
There some test failures with jquery: https://travis-ci.org/angular/angular.js/jobs/295785053

2017-11-01 15:50 UTC, curlydevil commented
@Narretz yes, I'm trying to understand why I have them passing locally at 4 browsers but not in CI...

2017-11-01 16:19 UTC, Narretz commented
Are you sure you are running `tests:jquery`?

2017-11-01 16:43 UTC, curlydevil commented
I was running `grunt autotest` to check in several browsers, and whole `grunt test` before push...

2017-11-01 18:35 UTC, petebacondarwin commented
I wonder if it is trying to convert `_t` to `T` when it should be `t` or vice versa?

2017-11-02 07:11 UTC, curlydevil commented
Checked how `<_t></_t>` behaves with 1.5.x - looks like it did not work this way, so I've dropped corresponding test, just leaving it as a `A` restriction check.

2017-11-02 08:47 UTC, curlydevil commented
Doh... `Error: Error updating Sauce pass/fail status: 'Could not send request: connect ETIMEDOUT 162.222.75.227:443'`
Is there a possibility to restart single stage or the branch build?

2017-11-02 09:58 UTC, Narretz commented
> Checked how <_t></_t> behaves with 1.5.x - looks like it did not work this way, so I've dropped corresponding test, just leaving it as an A restriction check.

Aren't we creating an inconsistent and undocumented behavior? Because afaik there's nothing about the handling of special characters at the start of a directive name in the docs.
Imo this looks like it was never explicitly supported, and if we support it it should be consistent and documented.

The docs:

>>> The normalization process is as follows:
>>> Strip x- and data- from the front of the element/attributes.
>>> Convert the :, -, or _-delimited name to camelCase.

It doesn't say that :, -, or _ are stripped from the front.

2017-11-02 18:06 UTC, gkalpak requested changes

2017-11-02 18:06 UTC, gkalpak commented on src/ng/compile.js
> +var PREFIX_REGEXP = /^((?:x|data)*[:\-_])/i;
Also, `PREFIX_REGEXP` is used to process `ng-attr-` attributes ([here][1] and this change affects that too.
IMO, this PR should restore the behavior of `directiveNormalize()` pre-73050cdda and not affect anything else.

[1]: https://github.com/curlydevil/angular.js/blob/6a20b352dba085c8e9f03c0c44ab67a4dd27e244/src/ng/compile.js#L2197

2017-11-06 08:40 UTC, curlydevil commented
@gkalpak looking through usage of new function, its implementation is actually correct for CSS, so changing it back might break the desired behaviour there... should I add yet another camelcasing method?

2017-11-06 10:55 UTC, gkalpak commented on src/ng/compile.js
> +    .replace(MOZ_HACK_REGEXP, 'Moz$1');
AFAICT, this was only necessary for CSS, so we don't need it here any more.

2017-11-06 10:55 UTC, gkalpak commented on src/ng/compile.js
> +function camelCase(name) {
Since this function is only used in `directiveNormalize()` it makes sense to inline the code there.

2017-11-06 10:56 UTC, gkalpak commented
> should I add yet another camelcasing method?

More or less. I.e. you just need to update `directiveNormalize()` to have the desired behavior (i.e. the bahavior it had for normalizing directive names before 73050cd.

2017-11-06 13:28 UTC, curlydevil commented
@gkalpak if current implementation is acceptable, please, approve it or un-require changes =)

2017-11-06 16:58 UTC, gkalpak requested changes

2017-11-06 16:58 UTC, gkalpak commented on src/ng/compile.js
> +var SPECIAL_CHARS_REGEXP = /([:\-_]+(.))/g;
Why the extra parenthesis? They are not needed afaict (and slow the RegExp down - theoretically :grinning:)

2017-11-06 16:58 UTC, gkalpak commented on src/ng/compile.js
> +    .replace(SPECIAL_CHARS_REGEXP, function(_, separator, letter, offset) {
Adjust arguments after removing extra parenthesis from RegExp (see previous comment).

2017-11-09 11:11 UTC, Narretz commented on test/ng/compileSpec.js
> +    it('should omit special chars before processing directive name', function() {
If this applies only to directives with restrict: 'A', then the test description should reflect that. Maybe even link to this issue in a comment.

2017-11-13 15:12 UTC, curlydevil commented
@Narretz @gkalpak @petebacondarwin any other ideas for improvement?

2017-11-13 15:26 UTC, gkalpak requested changes

2017-11-13 15:26 UTC, gkalpak commented on test/ng/compileSpec.js
> +        element = $compile('<div _t></div>')($rootScope);
The `element = ` parts are redundant.

2017-11-13 15:26 UTC, gkalpak commented on test/ng/compileSpec.js
> +    it('should omit special chars before processing attribute directive name', function() {
I would change "omit" to "ignore", because I think it bettr describes the behavior.

2017-11-14 11:07 UTC, gkalpak approved these changes

2017-11-17 10:55 UTC, merged