fix(input[number]): validate min/max against viewValue
angular/angular.js pull request #16325
Opened 2017-11-10 21:13 UTC by Narretz

This brings the validation in line with HTML5 validation and all other
validators.

Fixes #12761

BREAKING CHANGE

....

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix / normalization

**What is the current behavior? (You can also link to an open issue here)**
See #12761

**What is the new behavior (if this is a feature change)?**
validation of min / max against viewValue

**Does this PR introduce a breaking change?**
Yes

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](../DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](../DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

I believe the BC is moderate enough to be included in 1.7

To switch the validation to the modelValue, it's as easy as adding this into a directive:

```
var minValidator = ngModelCtrl.$validators.max;

        ngModelCtrl.$validators.max = function(modelValue, viewValue) {
          return minValidator(modelValue, modelValue);
        };
```

I could even publish this is as a configurable third party directive that allows you to do this for any validator.

2017-11-13 11:49 UTC, gkalpak approved these changes
LGTM (except for the missing "breaking change" notice on the commit message).

2017-11-13 11:49 UTC, gkalpak commented on test/ng/directive/inputSpec.js
> +        helper.changeInputValueTo('9');
Why not `10` (for symmetry with `min`)? 😢

2017-11-14 10:46 UTC, petebacondarwin commented on test/ng/directive/inputSpec.js
> +        var inputElm = helper.compileInput('<input type="number" num-parse ng-model="value" name="alias" min="10" />');
`num-parse` doesn't appear to be used anywhere

2017-11-14 10:47 UTC, petebacondarwin commented on test/ng/directive/inputSpec.js
> +        expect($rootScope.form.alias.$error.min).toBeFalsy();
Should we also have tests that check that we *do* get an error if the `viewValue` is bad but the `modelValue` is good?

2017-11-14 10:49 UTC, petebacondarwin requested changes
LGTM
 - we should add tests for bad viewValue -> good modelValue
 - we need a BC notice that includes the example directive for reverting the behaviour.

2017-11-14 16:35 UTC, Narretz commented
Updated with your suggestions!

2017-11-15 17:10 UTC, petebacondarwin approved these changes
Did you mean to capitalize "IF" in the commit message?

2017-11-17 11:28 UTC, merged