fix($cookies): remove the deprecated $cookieStore factory
angular/angular.js pull request #16465
Opened 2018-02-21 12:16 UTC by mgol

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Bug fix - a removal of a deprecated factory.

**What is the current behavior? (You can also link to an open issue here)**

The `$cookieStore` factory exists.

**What is the new behavior (if this is a feature change)?**

It doesn't.

**Does this PR introduce a breaking change?**

Yes.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [x] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

BREAKING CHANGE:

The $cookieStore has been removed. Migrate to the $cookie service. For simple
values it's enough to rename $cookieStore to $cookie; for object values you need
to use the `putObject` & `getObject` methods.

Before:
```js
$cookieStore.put('name1', 'simple value');
$cookieStore.get('name1'); // 'simple value'
$cookieStore.remove('name1');
$cookieStore.put('name2', {key: 'value'});
$cookieStore.get('name2'); // {key: 'value'}
$cookieStore.remove('name2');
```

After:
```js
$cookie.put('name1', 'simple value');
$cookie.get('name1'); // 'simple value'
$cookie.remove('name1');
$cookie.putObject('name2', {key: 'value'});
$cookie.getObject('name2'); // {key: 'value'}
$cookie.remove('name2');
```

2018-02-21 13:20 UTC, gkalpak requested changes
I would make the following changes to the commit message:

1. _fix($cookies)_ --> _fix(ngCookies)_ (because you are not really changing `$cookies`)
2. _$cookie_ --> _$cookies_ (everywhere)
3. It might be simpler to drop the differentiation between simple and object values and just recommend `$cookies.get/putObject()` (since this is what `$cookieStore` was using under the hood.
    At least, we should mention that `$cookies.get()` will not correctly retrieve simple values stored with `$cookieStore.put()` (since the stored values will be JSON-stringified and need to be JSON-parsed).

2018-02-21 13:20 UTC, gkalpak commented on docs/content/api/index.ngdoc
> +      The {@link ngCookies.$cookies $cookie} service is a convenient wrapper to store simple data within browser cookies.
_$cookie_ --> _$cookies_

2018-03-12 19:43 UTC, mgol commented
@gkalpak PR updated.

2018-03-12 20:14 UTC, gkalpak approved these changes

2018-03-12 22:09 UTC, jbedard approved these changes

2018-03-13 08:31 UTC, merged