fix(jqLite): make removeData() not remove event handlers
angular/angular.js pull request #16512
Opened 2018-03-26 22:54 UTC by mgol

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Bug fix but a breaking change as well.

**What is the current behavior? (You can also link to an open issue here)**

`removeData()` invoked on an element removes its event handlers as well.

**What is the new behavior (if this is a feature change)?**

`removeData()` removes just user-set `data`, not internal data storage used for event handling. This aligns jqLite with jQuery.

**Does this PR introduce a breaking change?**

Yes.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- ~~Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated~~ (the current behavior is not documented)
- [x] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

Fixes #15869

2018-03-27 09:06 UTC, gkalpak requested changes
No specs for `cleanData()` 😱
Also, in the commit message, I think you should change `angular.element.cleanData([elem])` to `angular.element.cleanData(elem)`.

2018-03-27 09:06 UTC, gkalpak commented on test/jqLiteSpec.js
> +    it('should allow to set data after removeData() with event handlers present', function() {
What about "with event handlers not present"?

2018-03-27 09:26 UTC, mgol commented
> No specs for cleanData() 😱

Good point. Although this method is still not officially documented in jQuery although it seems we'd like to change it.

> Also, in the commit message, I think you should change angular.element.cleanData([elem]) to angular.element.cleanData(elem).

The confusion comes from the fact jqLite code refes to bare DOM nodes as `element`. `cleanData` accepts an array-like of bare DOM nodes, not just jqLite objects so in this context `elem` is the correct choice as you noticed.

2018-03-27 09:28 UTC, mgol commented on src/jqLite.js
> +      jqLiteOff(nodes[i]);
This should be handled in the `cleanData` patch that used to be applied to jQuery only and that I moved to apply to jqLite as well.

2018-03-27 09:30 UTC, mgol commented on src/jqLite.js
> +  for (name in obj) {
That's taken from jQuery data handling:
https://github.com/jquery/jquery/blob/3.3.1/src/event.js#L290-L293
https://github.com/jquery/jquery/blob/3.3.1/src/data/Data.js#L142-L153

2018-03-27 20:12 UTC, gkalpak commented
BTW, should [this][1] also be changd to `cleanData()`?

[1]: https://github.com/mgol/angular.js/blob/acbeb82b24ec022b713aaf91ea45f9dd6b42b139/test/helpers/testabilityPatch.js#L23

2018-03-27 20:38 UTC, mgol commented
> BTW, should [this](https://github.com/mgol/angular.js/blob/acbeb82b24ec022b713aaf91ea45f9dd6b42b139/test/helpers/testabilityPatch.js#L23) also be changd to `cleanData()`?

Perhaps. `.empty()` will already call it for all descendants and `.removeData()` will remove user data on `body` so the only thing left are event handlers on `body`. But we're already not clearing handlers on `window` & `document` so it's not a full cleanup.

2018-03-28 12:27 UTC, gkalpak approved these changes

2018-03-28 12:27 UTC, gkalpak commented on test/jqLiteSpec.js
> +      browserTrigger(a, 'click');
Did you mean `b`? :grin:

2018-03-28 12:27 UTC, gkalpak commented on test/jqLiteSpec.js
> +      browserTrigger(a, 'click');
Did you mean `b`? :grin:

2018-03-28 12:27 UTC, gkalpak commented on test/jqLiteSpec.js
> +    it('should remove user data & event handlers on cleanData()', function() {
This description belongs to the test above and vice versa.

2018-03-28 12:37 UTC, mgol commented on test/jqLiteSpec.js
> +      browserTrigger(a, 'click');
Good eye. :)

2018-03-28 12:47 UTC, mgol commented
PR updated once again.

2018-03-31 22:50 UTC, jbedard approved these changes

2018-04-03 19:49 UTC, merged