feat(ngMock, ngMockE2E): add option to match latest definition for $h…
angular/angular.js pull request #16560
Opened 2018-05-09 14:38 UTC by Narretz

…ttpBackend request

Closes #16251
Closes #11637

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the current behavior? (You can also link to an open issue here)**
See #11637 

**What is the new behavior (if this is a feature change)?**
Config option to change the behavior

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ?] Fix/Feature: Tests have been added; existing tests pass

**Other information**:
First draft to discuss the API.
As noted in #16251, it's not possible (afaics) to put the option on the httpBackendProvider, because they cannot be decorated. It's also not useful to put the method on the ng.httpBackendProvider, because that's not where it's needed. The option to switch it directly from httpBackend could also be used to migrate tests step by step or use it only for new tests. Another option would be a new "$httpBackendMocksProvider" or similar (but I don't think that's very useful).

2018-05-17 18:54 UTC, gkalpak approved these changes
LGTM except for the lack of docs 📖

2018-05-17 18:55 UTC, petebacondarwin requested changes
Looks good but needs docs and perhaps another test?

2018-05-17 18:55 UTC, petebacondarwin commented on src/ngMock/angular-mocks.js
> +    while ((definition = definitions[matchLatestDefinition ? --i : ++i])) {
This is dangerous stuff due to the subtle difference between prefix and postfix operators. But given that we were doing this already I guess it'll be fine.

2018-05-17 18:55 UTC, petebacondarwin commented on src/ngMock/angular-mocks.js
> +
is this blank line needed / in keeping with the rest of the code?

2018-05-17 18:55 UTC, petebacondarwin commented on src/ngMock/angular-mocks.js
> +      matchLatestDefinition = value;
don't we normally return `this` when it is a setter to allow chaining?

2018-05-17 18:55 UTC, petebacondarwin commented on test/ngMock/angular-mocksSpec.js
> +    );
Do we already have tests for the order when this is false?

2018-05-17 18:55 UTC, petebacondarwin commented on test/ngMock/angular-mocksSpec.js
> +        expect(callback).toHaveBeenCalledOnce();
Should we check that it continues to work backwards if the last one doesn't match?

2018-05-17 18:55 UTC, petebacondarwin commented on src/ngMock/angular-mocks.js
> +  $httpBackend.matchLatestDefinition = function(value) {
I think we needed docs here.

2018-05-19 10:59 UTC, petebacondarwin approved these changes

2018-05-21 13:01 UTC, closed without merging