feat(form.FormController): add $getControls()
angular/angular.js pull request #16601
Opened 2018-06-15 15:36 UTC by Narretz

Fixes #14749
Closes #14517
Closes #13302

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feat

**What is the current behavior? (You can also link to an open issue here)**
there's no straight forward way to get all controls of a form

**What is the new behavior (if this is a feature change)?**
you can get a shallow copy of the form controls

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [x] Fix/Feature: Tests have been added; existing tests pass

**Other information**:
I decided against a synchronized copy (https://github.com/angular/angular.js/issues/14749#issuecomment-230451318) because I don't see the clear benefit over a simple shallow copy + is slightly more involved to implmenent.

2018-06-15 18:24 UTC, gkalpak requested changes
Mostly LGTM. Just a couple of minor suggestions.

2018-06-18 07:41 UTC, Narretz commented
@gkalpak Pr has been updated, PTAL

2018-06-18 13:17 UTC, gkalpak approved these changes

2018-06-18 13:17 UTC, gkalpak commented on test/ng/directive/formSpec.js
> +      var form = doc,
Unused variable.

2018-06-18 14:02 UTC, merged