docs(IoC): modified description about example
angular/angular.js pull request #16833
Opened 2019-02-16 13:59 UTC by kambleaa007

docs(IoC): modified description about example

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

2019-02-24 17:12 UTC, petebacondarwin requested changes

2019-02-24 17:12 UTC, petebacondarwin commented on docs/content/guide/di.ngdoc
> +Notice that `myModule` is independent as array is empty here.
```suggestion
Notice that `myModule`  depends upon no other modules as the second parameter is an empty array. 
```

2019-02-24 17:12 UTC, petebacondarwin commented on docs/content/guide/di.ngdoc
> +Dependent is always need dependency object to be injected inside it.
I don't understand this sentence. Remember that the previous code snippet is defining a module so it is not helpful to refer to "objects" here.

2019-02-24 17:12 UTC, petebacondarwin commented on docs/content/guide/di.ngdoc
> +so, injector now injects `$window` dependency inside `greeter` service.
I don't feel that this sentence makes sense. If anything it should appear before the previous sentence and should be something more like

> Notice that `greeter` is dependent on the `$window` service, which will be provided by the injector when it is instantiated.

2019-03-04 06:16 UTC, kambleaa007 reviewed
changed

2019-03-04 06:19 UTC, kambleaa007 commented
@petebacondarwin thanks,
Can you guide me how to make successful commit.

2019-03-04 09:02 UTC, mgol commented on docs/content/guide/di.ngdoc
> +Notice that `myModule`  depends upon no other modules as the second parameter is an empty array.
@petebacondarwin A double space got inserted here by accident:
```suggestion
Notice that `myModule` depends upon no other modules as the second parameter is an empty array. 
```

2019-03-04 09:23 UTC, mgol commented on docs/content/guide/di.ngdoc
> +You can use it when defining components
Is this change necessary?

2019-03-04 09:28 UTC, kambleaa007 reviewed
Helpful for beginners

2019-03-04 09:31 UTC, kambleaa007 reviewed
Im fine with this Thanks

2019-03-04 09:32 UTC, kambleaa007 commented
Hello all,
I think i'm gettin errors as i dont have write access to repo.
Does anybody help me in this??

2019-03-04 09:37 UTC, petebacondarwin commented
@kambleaa007 what errors? You should not need access to write to the main repository. You just write to your own fork,

2019-03-04 09:52 UTC, kambleaa007 commented
> @kambleaa007 what errors? You should not need access to write to the main repository. You just write to your own fork,

 Travis Giving me:- CLAs are signed, but unable to verify author consent

2019-03-04 09:57 UTC, petebacondarwin commented
This is because @mgol and I have made commits to this PR. You can ignore this error.

2019-03-04 10:12 UTC, kambleaa007 commented
> This is because @mgol and I have made commits to this PR. You can ignore this error.

That's great,
This is going to be interesting, as i learned a lot, this would be my first commit if it succeed hopefully.

2019-03-05 19:59 UTC, gkalpak approved these changes

2019-03-05 20:01 UTC, closed without merging

2019-03-05 20:02 UTC, gkalpak commented
I tweaked this a bit and merged. Thx, @kambleaa007 👍