chore: Update jQuery to v3.5.0
angular/angular.js pull request #17021
Opened 2020-04-29 22:11 UTC by aryehb

Update jQuery from v3.4.0 to v3.5.0 to resolve a possible XSS vulnerability.

See https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

**Does this PR fix a regression since 1.7.0, a security flaw, or a problem caused by a new browser version?**

Yes.

**What is the current behavior? (You can also link to an open issue here)**

See #17020.

**What is the new behavior (if this is a feature change)?**

Update jQuery to v3.5.0

**Does this PR introduce a breaking change?**

No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

Fixes #17020

2020-04-29 22:12 UTC, aryehb commented
@googlebot I signed it!

2020-04-30 10:55 UTC, gkalpak commented
Thx for making a PR.

Note that AngularJS does not depend on jQuery (not even as a peer dependency). It includes its own stripped down version of jQuery (jqLite) and can use jQuery if it is provided by the app developer (which is free to provide whichever version they want).

This PR updates a devDependency (used for testing in the AngularJS repo only) and therefore has no impact on the developers that use AngularJS in their apps.

Therefore (and given the fact that AngularJS is in [Long-Term Support mode][1]), I would lean towards not merging this, but let's see what others think.

[1]: https://docs.angularjs.org/misc/version-support-status#long-term-support

2020-04-30 11:05 UTC, mgol requested changes
As @gkalpak mentioned, this is a devDependency used for testing so there's no security issue. The only reason to update it is to make sure we're testing compatibility with recent jQuery versions.

There's going to be a 3.5.1 release soon with a fix for a 3.5.0 regression so I'd like to wait for that to reduce the PR churn.

2020-04-30 11:05 UTC, mgol commented on yarn.lock
> -"@types/node@^6.0.46":
`yarn.lock` has lots of changes that are not related to this update.

2020-04-30 14:10 UTC, aryehb commented
>Note that AngularJS does not depend on jQuery (not even as a peer dependency). It includes its own stripped down version of jQuery (jqLite) and can use jQuery if it is provided by the app developer (which is free to provide whichever version they want).

>This PR updates a devDependency (used for testing in the AngularJS repo only) and therefore has no impact on the developers that use AngularJS in their apps.

We were seeing jQuery v3.4.0 in our bundle even after updating our version of jQuery, so I thought it was due to AngularJS. I didn't realize that it's only used for testing. In that case, feel free to close this.

2020-04-30 14:32 UTC, aryehb commented
>We were seeing jQuery v3.4.0 in our bundle even after updating our version of jQuery

It looks like this was because the new version didn't update properly in our project.

2020-04-30 15:16 UTC, mgol commented
Cool, thanks for the update. Closing then.

2020-04-30 15:16 UTC, closed without merging