chore: update Copyrights to Google LLC
angular/angular.js pull request #17062
Opened 2020-08-08 00:51 UTC by Splaktar

# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**Does this PR fix a regression since 1.7.0, a security flaw, or a problem caused by a new browser version?**
No

**What is the current behavior?**
The Copyrights currently use the old name, Google, Inc. You can see [here](https://en.wikipedia.org/wiki/Google) that the new name is Google LLC and that Google, Inc. is the former name.

**What is the new behavior?**
Use Google LLC as the name. This is consistent with the [angular/angular LICENSE](https://github.com/angular/angular/blob/master/LICENSE#L3).

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

2020-08-08 09:33 UTC, Splaktar commented
These are just changes to comments. The Saucelabs unit test failures on Windows appear to be flakes.

2020-08-13 11:10 UTC, gkalpak requested changes
Thx, @Splaktar!

A couple of minor comments:
- I think we need to also update [docs/app/src/examples.js][1].
- It is worth noting in the commit message that a similar change was done in angular/angular#27880.

Otherwise lgtm :+1:

[1]: https://github.com/angular/angular.js/blob/0d14993d754e85df970ee25c9409c05b7043bbe7/docs/app/src/examples.js#L77

2020-09-30 18:14 UTC, Splaktar commented
Review feedback addressed. Thank you.

2020-09-30 18:39 UTC, Splaktar commented
Rebased to give CI another chance to pass the unit tests...

2020-09-30 18:43 UTC, gkalpak commented
Thx, @Splaktar! Can you please replace `#27880` with ` angular/angular#27880` in the commit message?

2020-09-30 18:47 UTC, Splaktar commented
Doh, sorry about that, done.

2020-09-30 19:15 UTC, gkalpak approved these changes
LGTM :shipit:

2020-09-30 21:43 UTC, gkalpak commented
CI has [successfully run][1] for this change as part of #17079.

[1]: https://app.circleci.com/pipelines/github/angular/angular.js/210/workflows/1bfbbf3f-0d30-4196-aa73-be0850438d4e

2020-09-30 21:59 UTC, closed without merging