Updated ReadMe
angular/angular.js pull request #17076
Opened 2020-09-30 16:11 UTC by akshit-dev101

# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**Does this PR fix a regression since 1.7.0, a security flaw, or a problem caused by a new browser version?**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

2020-09-30 18:19 UTC, Splaktar requested changes

2020-09-30 18:19 UTC, Splaktar commented on README.md
> +use good old HTML or HAML, Jade/Pug and friends! as your template languages and lets you extend there
I think that you can only use 1 template language at a time?

2020-09-30 18:19 UTC, Splaktar commented on README.md
> +use good old HTML or HAML, Jade/Pug and friends! as your template languages and lets you extend there
```suggestion
use good old HTML or HAML, Jade/Pug and friends! as your template language and lets you extend their
```

2020-09-30 18:20 UTC, Splaktar commented
Also from CI:
```
Invalid commit message, please fix:

- First line must be <type>(<scope>): <subject>
Need an opening parenthesis: (

Commit message was:

Updated ReadMe

See https://bit.ly/angular-guidelines
```
You can find more at https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits

2020-10-01 22:06 UTC, josephperrott commented
Closing this PR spam/invalid. It seems superfluous or not a meaningful, relevant change.


As you it appears that you may have created this PR as part of your participation in Hacktoberfest, Please review their note regarding quality before making additional PRs: [https://hacktoberfest.digitalocean.com/details#quality](https://hacktoberfest.digitalocean.com/details#quality)

2020-10-01 22:06 UTC, closed without merging